import { IDatabaseEntry } from '../../src/Interface/Interface'

const data: any[] = [   
    {   
        scientific_name: 'Dugong dugong',
        image_path: "Dugong",
        local_name: 'Dugong',
        IUCN_status: 'VU',
        size: 'Calf length: 1-1.3m, Adult length: 2.5m, Adult weight: 570kg',
        colour_pattern: 'The skin is thick and covered everywhere with fine hair, which give it a prickly appearance. The colouring of the dugong is variable as “dull brownish-grey” with the colour changing with size or age.',
        dorsal_fin: 'They do not have dorsal fins',
        description: 'The Dugong is the also known as a sea cow.  Their heads are cylindrical and tube-like bent downwards for munching on sea grass. The trunk is broadest in the waist region and narrows behind to form the tail fluke, which is horizontal and crescent-shaped. They have a peculiar surfacing where just the dorsal surface and a slow blow is sometimes visible, and a fluke that shows before a dive.',
        teeth_count: '6 on each quadrant of the jaws with one incisor on upper jaw that erupts as a tusk in males',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Dugongs live in shallow, sheltered coastal waters where there are sea grass beds. Current distribution in India is the Gulf of Kachchh, Palk Bay, Gulf of Mannar and the Andaman and Nicobar Islands.',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Megaptera novaeangliae',
        image_path: "Humpback-Whale",
        local_name: 'Humpback Whale',
        IUCN_status: 'LC',
        size: 'Calf length: 4.5m, Adult length: 11-17m in length, Average adult weight - 40000 kg',
        colour_pattern: 'Black or grey, with a white region on the throat and belly. The flippers are white underneath, sometimes above as well.',
        dorsal_fin: 'The dorsal fin is located less than one-third of the body length from the tail fluke notch. It may be small and triangular, or larger and sickle-shaped. It frequently includes a step or hump, giving the species its common name.',
        description: 'The body of a Humpback Whale is more robust than those of the other rorquals. The top of the head is flattened and covered by a number of fleshy knobs without a ridge. There is a round protuberance at the tip of the lower jaw. From above, the head is broad and rounded. The number of throat grooves is 14 to 35, extending to the navel. A Humpback’s flippers are very long, measuring about one-third of the total length. They are scalloped with knobs or bumps. Arabian sea Humpback whales are less than a 100 in population and limited to the Arabian Sea. The singing of Humpbacks at their breeding grounds is now famous. Their songs are audible from far away. These whales do not sing at their feeding grounds, though they do communicate with each other. They feed on swarming crustaceans and shoaling fish.',
        teeth_count: null,
        baleen_plate: '350-370 pairs',
        throat_grooves: 'The number of throat grooves is 14 to 35, extending to the navel.',
        seasonal_movement: 'Within Arabian sea',
        habitat_preferance: 'Found in coastal and continental shelf-edge waters.',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Balaenoptera musculus',
        image_path: "Blue-Whale",
        local_name: 'Blue Whale',
        IUCN_status: 'EN',
        size: 'Calf length: 7-8m, Adult length: 25-29m',
        colour_pattern: 'Bluish gray with mottling',
        dorsal_fin: 'Very small dorsal fin at 3/4th of the way from the rostrum tip',
        description: 'The Blue whale has a broad ‘U’ shaped head looking flat from the sides with a single central ridge.  70-118 (mostly 90-95) ventral pleats almost till the navel',
        teeth_count: null,
        baleen_plate: '260-400 pairs of baleen',
        throat_grooves: '70-118 (mostly 90-95) ventral pleats almost till the navel',
        seasonal_movement: 'Arabian sea - Bay of Bengal',
        habitat_preferance: 'Open-ocean species, seen close to shore for feeding and possibly breeding. The Arabian Sea probably also has the Pygmy Blue',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Balaenoptera edeni',
        image_path: "Bryde’s-Whale",
        local_name: 'Bryde’s Whale',
        IUCN_status: 'LC',
        size: 'Calf length: 4m, Adult length: 15-16.5 m, Adult weight: 40000 kg',
        colour_pattern: 'Dark gray',
        dorsal_fin: 'Tall and falcate dorsal fin at 3/4th of the way from the rostrum tip',
        description: "The Bryde's whale has a sleek body with a broad fluke with straight trailing edges. A pointed head with three ridges on the rostrum. columnar or bushy blow of variable height.",
        teeth_count: null,
        baleen_plate: '250-370 pairs of baleen',
        throat_grooves: '40- 70 (42-54 for the Arabian Sea) ventral pleats till the navel or beyond',
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Found offshore and near shore',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Balaenoptera omurai',
        image_path: "Omura's-Whale",
        local_name: "Omura's Whale",
        IUCN_status: 'DD',
        size: 'Calf length: 3.5-4 m, Adult male length: 9.6-10 m, Adult female length: 10.3-11.5 m, Adult weight: 20000 kg',
        colour_pattern: 'Two-toned body colouring with dark dorsal and light ventral body',
        dorsal_fin: 'A highly falcate and backswept dorsal fin is visible with blowhole at surfacing. The fin is more than 3/4th of the way from rostrum tip',
        description: "An Omura's whale has a small and streamlined body with a ‘V’ shaped head. A single prominent central ridge; Pale irregular chevrons are found anterior to the dorsal fin on both sides with the right chevron being more prominent. A conspicuous blaze on the right with 2 -3 stripes bisecting over the eye till the back; right lower jaw white; flipper anterior edges and inner surfaces white; broad fluke with straight trailing edge;",
        teeth_count: null,
        baleen_plate: '180-210 pairs of short and broad baleen, yellow white in the front and black in the back',
        throat_grooves: '80-90 ventral pleats extending beyond the navel',
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in nearshore in shallow continental shelves upto 202m.',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Mesoplodon pacificus',
        image_path: "Longman's-Beaked-Whale",
        local_name: "Longman's Beaked Whale",
        IUCN_status: 'DD',
        size: 'Calf length: 2.9 m, Adult max length: 6.5 m, Adult weight: Unknown',
        colour_pattern: 'Dorsal body is grey to brownish grey while the sides, underbelly and head is light in colour. Often, white scarring by cookie cutter sharks is visible on the body.',
        dorsal_fin: 'Relatively tall and falcate dorsal fin behind the midpoint of the back',
        description: 'Slender shaped body; prominent beak; no linear rake marks; protruding forehead with a crease between the beak and the melon;  flukes with no notch; small blunt flippers; ends of the blowhole pointing to the front;',
        teeth_count: 'A single pair of teeth i n the gums and not seen outside',
        baleen_plate: null,
        throat_grooves: 'V-shape d throat groove present',
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found offshore in deep oceans.',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Mesoplodon hotaula',
        image_path: "Deraniyagala’s-Beaked-Whale",
        local_name: "Deraniyagala’s Beaked Whale",
        IUCN_status: 'DD',
        size: 'Calf length:  2 m, Adult max length: 3.9-4.8 m. Adult weight: Unknown',
        colour_pattern: 'Dark gray with white scars. tip of the lower jaw is white',
        dorsal_fin: 'Small falcate dorsal fin 2/3rd of the way from the rostrum tip',
        description: 'Spindle shaped body and small narrow flippers. The mouthline is curved all along its length, shallow rising forehead?? arching mouthline in the posterior; blowhole is a crescent with ends pointing forward.',
        teeth_count: 'single pair of forward pointing conical tusks erupt only in the lower jaw of a dult males',
        baleen_plate: null,
        throat_grooves: 'V-shaped throat groove present',
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Distribution unknown but found offshore in deep waters.',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Mesoplodon ginkgodens',
        image_path: "Ginkgo-Toothed-Beaked-Whale",
        local_name: 'Ginkgo-Toothed Beaked Whale',
        IUCN_status: 'DD',
        size: 'Calf length: 2-2.5 m, Adult max length: 5.3 m, Adult max weight: Unknown',
        colour_pattern: 'Dark gray to black with white tips to the rostrum. White scars in adults',
        dorsal_fin: 'Small dorsal fin 2/3rd of the way from rostrum tip',
        description: 'Spindle shaped body and small narrow flippers. Small head, arched mouth line in males; ',
        teeth_count: 'Wide, flattened s-shaped tusks in the middle of the lower jaw that erupt only in adult males',
        baleen_plate: null,
        throat_grooves: 'One pair of throat grooves present',
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Distribution is unknown; found in offshore deeper waters.',
        type: 'Marine Mammals'
    },
    {
        scientific_name: 'Ziphius cavirostris',
        image_path: "Cuvier's-Beaked-Whale",
        local_name: "Cuvier's Beaked Whale",
        IUCN_status: 'LC',
        size: 'Calf length: 2.7m, Max adult length: 7m (males larger than females), Max adult weight: 3000 kg',
        colour_pattern: 'Grey to light rusty brown with cookie cutter scars and rake marks all over; males have a lot more white on head and upper back',
        dorsal_fin: 'Small falcate dorsal fin 2/3rd of the way from the rostrum tip',
        description: 'Spindle shaped body with a short beak; smooth sloping forehead (males show melon shape); small narrow flippers, mouthline is curved all along its length; slight concavity on the head',
        teeth_count: 'One pair of conical teeth erupt only at the tip of the lower jaw of adult males',
        baleen_plate: null,
        throat_grooves: 'A pair of V-shaped throat grooves present',
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found offshore and in deep waters close to steep continental slopes',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Mesoplodon densirostris',
        image_path: "Blainville's-Beaked-Whale",
        local_name: "Blainville's Beaked Whale",
        IUCN_status: 'LC',
        size: 'Calf length: 2-2.5m, Max adult length: 4.7m, Max adult weight: 1033 kg',
        colour_pattern: 'Grey to brownish grey; white scarring by cookie cutters and rake marks',
        dorsal_fin: 'Small dorsal fin 2/3rd of the way from the rostrum tip',
        description: 'Spindle shaped body; tapering flukes with no median notch; small narrow flippers; blowhole is a crescent with the hinge in the front; ',
        teeth_count: 'The mouthline is distinct with the posterior end highly arched; in males this arch is very wide and squarish with one pair of tusks erupting out of the mouth; the cheeks can rise above the upper jaw and the melon looks flat',
        baleen_plate: null,
        throat_grooves: 'Single pair of throat grooves present',
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in offshore deep waters 200m or more',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Physeter macrocephalus',
        image_path: "Sperm-Whale",
        local_name: 'Sperm Whale',
        IUCN_status: 'VU',
        size: 'Calf length: 3.5-4.5m, Max male length: 19.2m, Max female length: 12.5m, Max adult weight: 57000 kg (adult males weigh three times more than adult females)',
        colour_pattern: 'Black to brownish gray',
        dorsal_fin: 'Low knobby dorsal fin',
        description: 'Largest of toothed cetaceans; bulky body with wrinkles; head makes up 1/3rd of body length; head looks squarish from the side; lower jaw is very narrow compared to the upper jaw; only lower jaw has teeth; single s-shaped blowhole a bit left of the head; flippers are short and spatula shaped; fluke is broad with a straight trailing edge and has many notches; bushy blow, angled forward to the left',
        teeth_count: '18-26 pairs of teeth in lower jaw',
        baleen_plate: null,
        throat_grooves: '2-10 short throat grooves',
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found near the continental slope, in waters deeper than 1000m, and submarine canyons close to shore.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Kogia sima',
        image_path: "Dwarf-Sperm-Whale",
        local_name: 'Dwarf Sperm Whale',
        IUCN_status: 'LC',
        size: 'Calf length: 1m, Max adult length: 2.7m (males larger than females), Max adult weight: 272 kg',
        colour_pattern: 'Dark gray to brownish black on the upper side; a mark behind the eye that looks like a false gill slit',
        dorsal_fin: 'Tall falcate dorsal fin at the middle of the back',
        description: 'Robust body; a mark behind the eye that looks like a false gill slit; shark-like head; small and narrow lower jaw; small flippers closer to the head; blowhole is located > 10% away from the rostrum tip.',
        teeth_count: 'Lower jaw has 7-12 pairs of teeth; upper jaw sometimes have 3 pairs of teeth',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in offshore waters',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Kogia breviceps',
        image_path: "Pygmy-Sperm-Whale",
        local_name: 'Pygmy Sperm Whale',
        IUCN_status: 'LC',
        size: 'Calf length: 1.2m, Max adult length: 2.7-3.8m (females larger than males), Max adult weight: 450 kg',
        colour_pattern: 'Dark gray to brownish black on the upper side; a mark behind the eye that looks like a false gill slit',
        dorsal_fin: 'Small curved dorsal fin well behind the middle of the back',
        description: 'Robust body; a mark behind the eye that looks like a false gill slit; shark-like head; small and narrow lower jaw; small flippers closer to the head; a slight hump is present between blowhole and dorsal fin; blowhole is located >10% away from the rostrum tip',
        teeth_count: 'Lower jaw has 10-16 pairs of teeth',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found on the continental slope and in deeper waters. Not as common as the Dwarf sperm whale.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Orcaella brevirostris',
        image_path: "Irrawaddy-Dolphin",
        local_name: 'Irrawaddy Dolphin',
        IUCN_status: 'EN',
        size: 'Calf length: 1m, Max adult length: 2.5m, Max adult weight: 130 kg',
        colour_pattern: 'Steel gray',
        dorsal_fin: 'Knob like dorsal fin just behind the midpoint of the body',
        description: 'Rounded snout; beak absent; flippers are large and paddle shaped; neck crease present in adults',
        teeth_count: 'Upper jaw 8-19, Lower jaw 13-14 pairs.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in coastal waters, lagoons, estuaries and rivers. Current distribution in India includes Chilika lagoon, coastal waters of northern Orissa and West Bengal including Bhitarkanika and the Sundarbans.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Globicephala macrorhynchus',
        image_path: "Short-Finned-Pilot-Whale",
        local_name: 'Short-Finned Pilot Whale',
        IUCN_status: 'LC',
        size: 'Calf length: 1.4-1.9m, Max male length: 7.2m, Max female length: 5.5m, Max adult weight: 3600 kg',
        colour_pattern: 'Black to brownish gray',
        dorsal_fin: 'A light coloured saddle pattern behind the dorsal fin; large rounded dorsal fin, low and just in front of the midpoint of the back',
        description: 'Anchor shaped light patch on the chest; two light streaks from the base of the dorsal fin around the blow hole dropping to the eyes; a light coloured saddle pattern behind the dorsal fin; rounded snout; bulbous head almost squarish in adults; long, sickle shaped tapering flippers; males much bigger than females with a prominent post anal keel and more falcate flippers with a wider base.',
        teeth_count: '7-9 pairs of teeth in each jaw',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in deep offshore waters and around oceanic islands where nearshore waters are deep.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Orcinus orca',
        image_path: "Killer-Whale",
        local_name: 'Killer Whale',
        IUCN_status: 'DD',
        size: 'Calf length: 2.1-2.6m, Max male length: 9.8m, Max female length: 8.5m, Max adult weight: 7500-10000 kg',
        colour_pattern: 'Easy to identify black-white colour pattern; light coloured saddle behind the dorsal fin.',
        dorsal_fin: 'Easily identifiable by its very large triangular erect dorsal fin (male dorsal fin more than 2m tall; females have a curved fin upto 0.9m tall)',
        description: 'Largest of dolphins; robust; blunt snout; no prominent beak;',
        teeth_count: '10-14 pairs of teeth in each jaw.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'A cosmopoliltan species usually sighted nearshore and offshore.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Pseudorca crassidens',
        image_path: "False-Killer-Whale",
        local_name: 'False Killer Whale',
        IUCN_status: 'NT',
        size: 'Calf length: 1.5-2.1m, Max male length: 6m, Max female length: 5m, Max adult weight: 2000 kg',
        colour_pattern: 'Black to greyish black; light gray patch on the chest and belly.',
        dorsal_fin: 'Dorsal fin is tall, falcate with a rounded tip, at the midpoint of the back.',
        description: 'Very faint cape tapering to the keel; long slender body; rounded snout with a softly sloping melon; beak absent; beak absent; flippers are long with a slight hump in the leading edge giving them a S-shape.',
        teeth_count: '7-12 pairs of teeth in each jaw.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in deep offshore waters and around oceanic islands where nearshore waters are deep.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Feresa attenuata',
        image_path: "Pygmy-Killer-Whale",
        local_name: 'Pygmy Killer Whale',
        IUCN_status: 'LC',
        size: 'Calf length: 80cm, Max adult length: 2.6m, Max adult weight: 225 kg',
        colour_pattern: 'Black to greyish black; lips and beak tips are white',
        dorsal_fin: 'Dorsal fin is tall, falcate rising at a low angle at the midpoint of the back',
        description: 'Long body, robust before dorsal fin and slender after; rounded snout with a sloping melon; beak absent; flippers are long with rounded tips; light gray cape dipping just under the dorsal fin is prominent;',
        teeth_count: 'Upper jaw 8-11 pairs of teeth and Lower jaw 11-13 pairs.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in deep offshore waters and around oceanic islands where nearshore waters are deep.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Peponocephala electra',
        image_path: "Melon-Headed-Whale",
        local_name: 'Melon-Headed Whale',
        IUCN_status: 'LC',
        size: 'Calf length: 1m, Max adult length: 2.6m, Max adult weight: 275 kg',
        colour_pattern: 'Greyish black; lips and beak tips are white',
        dorsal_fin: 'Dorsal fin is tall, falcate at the midpoint of the back',
        description: 'Long slender body; rounded snout with a melon; slight hint of a beak; flippers are long, pointed and sickle shaped; light gray cape dipping (more deeply than in Pygmy killer whales) just under the dorsal fin is prominent; lighter urinogenital patch.',
        teeth_count: '20-25 pairs of teeth in each jaw.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in deep offshore waters and around oceanic islands where nearshore waters are deep.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Grampus griseus',
        image_path: "Risso's-Dolphin",
        local_name: "Risso's Dolphin",
        IUCN_status: 'LC',
        size: 'Calf length: 1-1.5m, Max adult length: 3.8m, Max adult weight: 500 kg',
        colour_pattern: 'Greyish white; most of the body is heavily scarred by rake marks and looks grey to white.',
        dorsal_fin: 'Dorsal fin is tall, slender, erect at the midpoint of the back',
        description: 'Body robust; blunt head; mouthline slopes upwards; a melon with a more squarish look than round; long and pointed flippers; the tail stock is very slender compared to the front of the body;',
        teeth_count: 'Lower jaw has 2-7 pairs of teeth and upper jaw has 1 pair of teeth or none; teeth are usually always worn out.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found off the continental slope and in deeper regions of the outer shelf.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Steno bredanensis',
        image_path: "Rough-Toothed-Dolphin",
        local_name: 'Rough-Toothed Dolphin',
        IUCN_status: 'LC',
        size: 'Calf length: 1m, Max adult length: 2.65m, Max adult weight: 155 kg',
        colour_pattern: 'Greyish black on top, pinkish belly and a lighter grey cape on the sides which dips under the dorsal fin.',
        dorsal_fin: 'Dorsal fin is tall, slender, erect at the midpoint of the back; long beak',
        description: 'Robust body; pointed conical head; a gently sloping melon with no crease; long beak; flippers are large, pointed; belly, lips and lower jaw are mottled white; dark eye patch;',
        teeth_count: '19-28 pairs of teeth in each jaw with wrinkled edges to the teeth.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in deep oceanic waters. Very rare in Indian waters.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Sousa plumbea',
        image_path: "Indian-Ocean-Humpback-Dolphin",
        local_name: 'Indian Ocean Humpback Dolphin',
        IUCN_status: 'EN',
        size: 'Calf length: 1m, Max male length: 2.8m, Max female length: 2.6m, Max adult weight: 280 kg',
        colour_pattern: 'Greyish black on top, pinkish belly',
        dorsal_fin: 'Dorsal fin is short and pointed sitting on a large hump just in front of the midpoint of the body',
        description: 'Robust body; a bulbous melon with a distinct crease; moderately long beak; flippers and flukes are large, with rounded tips; belly, lips and lower jaw are mottled pink; dark eye patch; adults have bigger humps, specially in males.',
        teeth_count: 'Upper jaw has 33-39 pairs of teeth and lower jaw has 31-37 pairs of teeth',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Found in near shore shallow waters of depths less than 30 m, close to river mouths and in estuaries. The most common species along the western coast of India.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Sousa chinensis',
        image_path: "Indo-Pacific-Humpback-Dolphin",
        local_name: 'Indo-Pacific Humpback Dolphin',
        IUCN_status: 'VU',
        size: 'Calf length: 1m, Max adult length: 2.7m, Max adult weight: 240 kg',
        colour_pattern: 'Greyish pink with more pink on sides, around the mouth and a pinkish belly.',
        dorsal_fin: 'Dorsal fin is short',
        description: 'Robust body; a bulbous melon with a prominent crease; gently sloping hump under the fin is not as pronounced as in S. plumbea; fin at the midpoint of the back; long beak; flippers and flukes have rounded pointy tips',
        teeth_count: 'Upper jaw has 32-38 pairs of teeth and lower jaw has 29-38 pairs of teeth.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Found on the east coast of India. Area of overlap between S. plumbea and chinensis is speculated to be in southeast India. Found in near shore shallow waters of depths less than 30 m, close to river mouths and in estuaries.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Tursiops aduncus',
        image_path: "Indo-Pacific-Bottlenose-Dolphin",
        local_name: 'Indo-Pacific Bottlenose Dolphin',
        IUCN_status: 'NT',
        size: 'Calf length: 85-112 cm, Adult length: 2.7m, Adult weight: 230kg',
        colour_pattern: 'Grey on top with lighter grey cape on the sides and blaze rising up towards the dorsal fin. Calves have a pinkish belly while the same is spotted black in adults.',
        dorsal_fin: 'Dorsal fin is tall with a broad base.',
        description: 'The Indo-Pacific bottlenose has a robust body with a bulbous head and a gently sloping forehead. The beak is long with lower jaw slightly longer than upper jaw. Flippers are small, pointed and a prominent crease is present.',
        teeth_count: '21-29 pairs of teeth in each jaw',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Found in nearshore waters. Indian waters may also have Tursiops truncatus (the common bottlenose dolphin) found on the shelf but in deeper waters. T. truncatus has a shorter beak, a more robust body, a more falcate fin, and no ventral spots.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Stenella attenuata',
        image_path: "Pan-Tropical-Spotted-Dolphin",
        local_name: 'Pan-Tropical Spotted Dolphin',
        IUCN_status: 'LC',
        size: 'Calf length: 90cm, Adult lenght: averages at 2m. Adult weight: 110 kg',
        colour_pattern: 'Pantropical spotted dolphins are grey overall, darker above and on the upper flanks, and lighter on the belly and lower flanks. The body is usually spotted, though spotting varies with regions, with white spots above and dark spots below. The spotting increases with age and region. Newborn spotted dolphins are unspotted, having a dark grey back with soft edges and a light belly',
        dorsal_fin: 'They have a beak that is moderately long, and a tall, falcate dorsal fin which is centrally placed.',
        description: 'At sea, the unique presence of a marked bridle, uniform dark cape on the dorsal side, and presence of a dark flipper line help in identifying the species.  Due the presence of a distinct bridle it was also known as the bridled Dolphin. They have 35-40 tiny pointed teeth on each side of both slender jaws. They are surface feeders, feeding on various species of fish and squid.',
        teeth_count: 'They have 35-40 tiny pointed teeth on each side of both slender jaws.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Pan-tropical spotted dolphins are found in tropical oceans with warm surface temperatures, both in coastal and offshore regions. Coastal forms are generally larger and more heavily spotted than those which live offshore.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Stenella longirostris',
        image_path: "Spinner-Dolphin",
        local_name: 'Spinner Dolphin',
        IUCN_status: 'DD',
        size: 'Calf length: 75-80cm, Dwarf spinner length: 1.38-1.58m, Max adult length: 2-2.3m, Max adult weight: 82 kg',
        colour_pattern: 'Greyish black on top, a lighter grey band running along the sides and a white belly (tripartite pattern); dark eye stripe from eye to crease and eye to flipper; upper beak is dark and lower beak is white with a black tip to upper beak',
        dorsal_fin: 'Dorsal fin is tall, slender, erect at the mid-point of the back',
        description: 'Spinner dolphins have a very slender body with a gently sloping forehead. A crease is present and the beak is very long. Their flippers are slender and pointed. Indian waters can have dwarf spinner dolphins, Stenella longirostris roseiventris and Gray’s spinner dolphins, Stenella longirostris longirostris. ',
        teeth_count: '40-62 pairs of teeth in each jaw; (dwarf spinner dolphins have 41-52 pairs of teeth in each jaw)',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Found in deep offshore waters and around oceanic islands where nearshore waters are deep.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Stenella coeruleoalba',
        image_path: "Striped-Dolphin",
        local_name: 'Striped Dolphin',
        IUCN_status: 'LC',
        size: 'Calf length: 93-100 cm, Adult length: 2.56 m, Adult weight: 156kg',
        colour_pattern: 'Greyish black on top with a dark cape. Lighter grey on the side with a blaze towards the front of the dorsal fin. A dark stripe runs from the eye to anus and eye to flipper. Upper beak is dark and lower beak is white with a black tip.',
        dorsal_fin: 'The dorsal fin is triangular with a broad base at the midpoint of the back.',
        description: 'The body of the Striped dolphin is not as slender as that of other Stenella. They have a gently sloping forehead and a moderately long beak. The flippers are slender and pointed and a crease is present',
        teeth_count: '40-55 pairs of teeth in each jaw',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in oceanic deep waters.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Delphinus capensis tropicalis',
        image_path: "Indo-Pacific-Common-Dolphin",
        local_name: 'Indo-Pacific Common Dolphin',
        IUCN_status: 'LC',
        size: 'Calf length: 80-100cm, Adult length: 2.6 m, Adult weight: 235kg',
        colour_pattern: 'Greyish black on top, a lighter white belly with a prominent v-shaped hour glass pattern under the dorsal fin and a yellow blaze above the flipper',
        dorsal_fin: 'The dorsal fin is tall, slender, falcate and at the midpoint of the back',
        description: 'The Indo-Pacific common dolphin has a very slender body with a gently sloping forehead. They have a very long beak and the flippers are long, slender and pointed. Crease is present',
        teeth_count: 'Upper jaw has 54-67 pairs of teeth and lower jaw has 52-64 pairs of teeth',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Found in deeper waters of the continental shelf and on the slope, sometimes in near-shore deep waters.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Lagenodelphis hosei',
        image_path: "Fraser's-Dolphin",
        local_name: "Fraser's Dolphin",
        IUCN_status: 'LC',
        size: 'Calf length: 1-1.1 m, Adult male length- 2.7 m, Adult female length: 2.6m, Adult weight - 210 kg',
        colour_pattern: 'Greyish on top with pink belly and a lighter grey band running from the face to the anus. A grey stripe is visible from the middle of the lower jaw to the flipper while a dark stripe is visible from apex of melon to tip of the upper jaw. Tip of the beak is dark.',
        dorsal_fin: 'The dorsal fin is short, triangular and erect at the midpoint of the back.',
        description: "Fraser's dolphins have a very stocky body with a gently sloping forehead. A crease is present between the melon and the beak. The beak itself is short and stubby. The flippers are long and pointed at the tips. The trailing edges of the fluke are distinctly concave.",
        teeth_count: '38-44 pairs of teeth in each jaw.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Unknown',
        habitat_preferance: 'Oceanic species found in deep offshore waters.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Neophocaena phocaenoides',
        image_path: "Indo-Pacific-Finless-Porpoise",
        local_name: 'Indo-Pacific Finless Porpoise',
        IUCN_status: 'VU',
        size: 'Calf length: 75-85cm, Adult size: 1.5m, Adult weight: 60kg',
        colour_pattern: 'Dark grey to brown grey; absent; tubercle patch on the back with rows of 10-25 tubercles;',
        dorsal_fin: 'Dorsal fin is absent',
        description: 'Indo-Pacific finless porpoises have a torpedo shaped body with a bulbous head and a rounded snout. There is no beak but long falcate flippers are present. A notched tail fluke',
        teeth_count: 'Spade-shaped teeth with 15-22 pairs of teeth in each jaw.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Found all along the coast of India including the Sundarbans, in near shore waters and in estuaries.',
        type: 'Marine Mammals'
    },
    {

        scientific_name: 'Platanista gangetica',
        image_path: "South-Asian-River-Dolphin",
        local_name: 'South Asian River Dolphin',
        IUCN_status: 'EN',
        size: 'Calf length: 70-90cm, Adult male length: 1.6-2.6 m, Adult female length- 1.6-2.4 mm, Adult max weight - 85kg',
        colour_pattern: 'Top and back is light brown to brownish grey while the underbelly is light',
        dorsal_fin: 'Dorsal fin is low, small, triangular, wide-based and about 2/3rd the way from the rostrum tip;',
        description: 'The South Asian River dolphin has a stocky body and a long slender beak with a flattened tip. The beak is longer in female and relatively shorter in males. There exists a prominent crease between the beak and melon with ridge on the melon. A single slit signifies the blowhole. The eyes are like pinholes and the flukes are broad with concave inner margins and a prominent notch. The species has broad flippers with square distal ends.',
        teeth_count: 'Upper jaw has 26-39 pairs of teeth and lower jaw has 26-35 pairs of teeth.',
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: 'Resident populations',
        habitat_preferance: 'Found in the Indus, Ganges, Brahmaputra, Meghna and Karnaphuli Sangu rivers and their tributaries. P.g.minor is found in the Indus drainage in Pakistan and the Beas river in India. P.g. gangetica is found in the rest of species distribution range.',
        type: 'Marine Mammals'
    },

    
]

data.sort((a, b) => a.scientific_name.localeCompare(b.scientific_name))

const d: IDatabaseEntry[] = data.map((e,i) => {
    return {
        id: i.toString(),
        ...e
    }
})

export default d
