import { IDatabaseEntry } from '../../src/Interface/Interface'

const data: any[] = [
    {   
        scientific_name: "Dugong dugong" ,
        image_path: "Dugong" ,
        local_name: "Dugong" ,
        IUCN_status: "VU" ,
        description: "Kepala silinder dan seperti tabung ditekuk ke bawah untuk mengunyah rumput laut. Batangnya terluas di daerah pinggang dan menyempit di belakang untuk membentuk kebetulan ekor, yang horizontal dan berbentuk bulan sabit. Mereka memiliki permukaan aneh di mana hanya permukaan punggung dan pukulan lambat kadang-kadang terlihat, dan kebetulan yang muncul sebelum menyelam." ,
        size: "Panjang saat lahir: 1-1.3m, Panjang dewasa: 2.5-2.7m, Berat dewasa: 570 Kg" ,
        colour_pattern: "Abu-abu coklat kotor" ,
        dorsal_fin: "Mereka tidak memiliki sirip punggung" ,
        teeth_count: "Enam gigi di setiap kuadran rahang dengan satu gigi seri di rahang atas yang erupsi sebagai gading pada laki-laki" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Dugong hidup di perairan pantai yang dangkal dan terlindung di mana terdapat padang lamun Distribusi saat ini di India adalah Teluk Kachchh, Teluk Palk, Teluk Mannar dan Kepulauan Andaman dan Nicobar" ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "Megaptera novaeangliae" ,
        image_path: "Humpback-Whale" ,
        local_name: "Paus bungkuk" ,
        IUCN_status: "LC" ,
        description: "Tubuh yang lebih kuat daripada rorquals lainnya. Bagian atas kepala diratakan dan ditutupi oleh sejumlah kenop berdaging tanpa tonjolan. Terdapat tonjolan bulat di ujung rahang bawah. Dari atas, kepalanya lebar dan bulat. Jumlah lekukan tenggorokan adalah 14 hingga 35, memanjang hingga pusar. Sirip sangat panjang, berukuran sekitar sepertiga dari total panjang tubuh. Mereka bergigi dengan kenop atau gundukan. Mereka memakan krustasea yang berkerumun dan ikan shoaling." ,
        size: "Panjang saat lahir: 4.3m, Panjang dewasa: 11-17m, Berat dewasa: 40000 Kg" ,
        colour_pattern: "Hitam atau abu-abu, dengan daerah putih di tenggorokan dan perut. Sirip berwarna putih di bawahnya, terkadang di atas juga." ,
        dorsal_fin: "Sirip punggung terletak kurang dari sepertiga panjang tubuh dari takik kebetulan ekor. Mungkin kecil dan berbentuk segitiga, atau lebih besar dan berbentuk sabit. Sering kali memiliki undakan atau punuk, memberikan nama umum spesies ini." ,
        teeth_count: null,
        baleen_plate: "350-370 pasang" ,
        throat_grooves: "Jumlah alur tenggorokan adalah 14 hingga 35, memanjang ke pusar" ,
        seasonal_movement: "Di dalam laut Arab" ,
        habitat_preferance: " Ditemukan di perairan pesisir dan tepi landas kontinen" ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "otot Balaenoptera" ,
        image_path: "Blue-Whale" ,
        local_name: "Paus biru" ,
        IUCN_status: "EN" ,
        description: "Memiliki kepala berbentuk 'U' yang lebar, tampak rata dari samping dengan satu lekukan di tengah. Pukulannya berbentuk kolom." ,
        size: "Panjang saat lahir: 7-8m, Panjang dewasa: 25-29m, Berat dewasa: 72000-135000 Kg" ,
        colour_pattern: "Abu-abu kebiruan dengan bintik-bintik." ,
        dorsal_fin: "Sirip punggung sangat kecil pada 3/4 dari ujung mimbar" ,
        teeth_count: null,
        baleen_plate: "260-400 pasang balin" ,
        throat_grooves: "70-118 (kebanyakan 90-95) lipatan perut hampir sampai pusar" ,
        seasonal_movement: "Laut Arab - Teluk Benggala" ,
        habitat_preferance: "Spesies laut terbuka, terlihat dekat pantai untuk mencari makan dan mungkin berkembang biak. Laut Arab mungkin juga memiliki paus Biru Pygmy." ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "Balaenoptera edeni" ,
        image_path: "Bryde’s-Whale" ,
        local_name: "Paus Bryde" ,
        IUCN_status: "LC" ,
        description: "Memiliki bodi ramping dengan fluke lebar dengan trailing edge lurus. Kepala runcing dengan tiga tonjolan di mimbar. Pukulannya berbentuk kolom atau lebat dengan ketinggian yang bervariasi." ,
        size: "Panjang saat lahir: 4m, Panjang dewasa: 15-16.5m, Berat dewasa: 40000 Kg" ,
        colour_pattern: "Abu-abu gelap" ,
        dorsal_fin: " Sirip punggung tinggi dan melengkung pada 3/4 dari ujung mimbar" ,
        teeth_count: null,
        baleen_plate: "250-370 pasang balin" ,
        throat_grooves: "40-70 (42-54 untuk Laut Arab) lipatan perut sampai pusar atau lebih" ,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Ditemukan di lepas pantai dan dekat pantai" ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "Balaenoptera omurai" ,
        image_path: "Omura's-Whale" ,
        local_name: "Paus Omura" ,
        IUCN_status: "DD" ,
        description: "Memiliki tubuh kecil dan ramping dengan kepala berbentuk 'V' dengan satu punggungan tengah yang menonjol. Chevron pucat tidak beraturan ditemukan di anterior sirip punggung di kedua sisi dengan chevron kanan lebih menonjol. Kobaran api yang mencolok di sisi kanan dengan 2 -3 garis membelah mata hingga ke belakang. Rahang bawah kanan berwarna putih. Tepi anterior sirip dan permukaan bagian dalam berwarna putih. Flukenya lebar dengan trailing edge yang lurus." ,
        size: "Panjang saat lahir: 3.5-4m, Panjang dewasa: 9.6-11.5m, Berat dewasa: 20000 Kg" ,
        colour_pattern: "Warna tubuh dua warna dengan bagian punggung gelap dan bagian perut terang." ,
        dorsal_fin: "Sirip punggung yang sangat melengkung dan melengkung ke belakang terlihat dengan lubang sembur di permukaan Sirip lebih dari 3/4 dari ujung mimbar" ,
        teeth_count: null,
        baleen_plate: "180-210 pasang balin pendek dan lebar, putih kuning di depan dan hitam di belakang" ,
        throat_grooves: "80-90 lipatan ventral memanjang di luar pusar" ,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di dekat pantai di landas kontinen dangkal hingga 202m" ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "Mesoplodon pacificus" ,
        image_path: "Longman's-Beaked-Whale" ,
        local_name: "Paus berparuh Longman" ,
        IUCN_status: "DD" ,
        description: "Memiliki tubuh berbentuk ramping dengan paruh yang menonjol dan dahi yang menonjol dengan lipatan antara paruh dan melon. Tidak ada tanda penggaruk linier dan cacing tidak memiliki takik. siripnya kecil tumpul. Ujung lubang sembur mengarah ke depan." ,
        size: "Panjang saat lahir: 2.9m, Panjang dewasa: 6.5m, Berat dewasa: Unknown" ,
        colour_pattern: "Tubuh bagian punggung berwarna abu-abu sampai abu-abu kecoklatan sedangkan bagian samping, perut dan kepala berwarna terang. Seringkali, jaringan parut putih oleh hiu pemotong kue terlihat di tubuh." ,
        dorsal_fin: "Sirip punggung relatif tinggi dan melengkung di belakang titik tengah punggung" ,
        teeth_count: "Sepasang gigi di gusi dan tidak terlihat di luar" ,
        baleen_plate: null,
        throat_grooves: "V-bentuk d alur tenggorokan hadir" ,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di lepas pantai di laut dalam" ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "Mesoplodon hotaula" ,
        image_path: "Deraniyagala’s-Beaked-Whale" ,
        local_name: "Paus berparuh Deraniyagala" ,
        IUCN_status: "DD" ,
        description: "Memiliki tubuh berbentuk gelendong dan sirip kecil yang sempit. Mulutnya melengkung sepanjang panjangnya, melengkung di posterior. Memiliki dahi yang naik dengan lembut dan lubang sembur berbentuk bulan sabit dengan ujung mengarah ke depan." ,
        size: "Panjang saat lahir: 2m, Panjang dewasa: 3.9-4.8m, Berat dewasa: Unknown" ,
        colour_pattern: "Abu-abu gelap dengan bekas luka putih. Ujung rahang bawah berwarna putih." ,
        dorsal_fin: "Sirip punggung falcate kecil 2/3 dari ujung mimbar" ,
        teeth_count: "Sepasang gading berbentuk kerucut yang mengarah ke depan hanya muncul di rahang bawah jantan dewasa" ,
        baleen_plate: null,
        throat_grooves: " Alur tenggorokan berbentuk V hadir" ,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Distribusi tidak diketahui tetapi ditemukan di lepas pantai di perairan dalam" ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "Mesoplodon ginkgodens" ,
        image_path: "Ginkgo-Toothed-Beaked-Whale" ,
        local_name: "Paus paruh bergigi ginkgo" ,
        IUCN_status: "DD" ,
        description: "Memiliki tubuh berbentuk gelendong dengan sirip kecil yang sempit. Kepala kecil dengan garis mulut melengkung pada pria." ,
        size: "Panjang saat lahir: 2-2.5m, Panjang dewasa: 5.3m, Berat dewasa: Unknown" ,
        colour_pattern: "Abu-abu gelap sampai hitam dengan ujung putih ke mimbar. Bekas luka putih pada orang dewasa." ,
        dorsal_fin: "Sirip punggung kecil 2/3 dari ujung mimbar" ,
        teeth_count: "Gading lebar berbentuk huruf S di tengah rahang bawah yang meletus hanya pada pria dewasa." ,
        baleen_plate: null,
        throat_grooves: "Sepasang alur tenggorokan hadir" ,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Distribusi tidak diketahui; ditemukan di perairan lepas pantai yang lebih dalam" ,
        type: "Marine Mammals" ,
    },
    {           
        scientific_name: "Ziphius cavirostris" ,
        image_path: "Cuvier's-Beaked-Whale" ,
        local_name: "Paus berparuh Cuvier" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh berbentuk gelendong dengan paruh pendek dan sirip kecil yang sempit. Ada dahi miring halus (jantan menunjukkan bentuk melon) dengan garis mulut cekung yang melengkung sepanjang panjangnya." ,
        size: "Panjang saat lahir: 2.7m, Panjang dewasa: 6-7m, Berat dewasa: 3000 Kg" ,
        colour_pattern: "Abu-abu hingga coklat muda berkarat dengan bekas luka pemotong kue dan bekas penggaruk di mana-mana. Laki-laki memiliki lebih banyak putih di kepala dan punggung atas." ,
        dorsal_fin: "Sirip punggung falcate kecil 2/3 dari ujung mimbar" ,
        teeth_count: "Sepasang gigi berbentuk kerucut hanya muncul di ujung rahang bawah pria dewasa." ,
        baleen_plate: null,
        throat_grooves: "Sepasang alur tenggorokan berbentuk V hadir" ,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di lepas pantai dan di perairan dalam dekat dengan lereng benua yang curam" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Mesoplodon densirostris" ,
        image_path: "Blainville's-Beaked-Whale" ,
        local_name: "Paus Paruh Blainville" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh berbentuk gelendong dengan lubang sembur berbentuk bulan sabit yang berengsel di ujung anterior. Cacing ekornya meruncing tanpa lekukan median dan siripnya kecil dan sempit. Garis mulutnya berbeda dengan ujung posterior sangat melengkung; pada laki-laki lengkungan ini sangat lebar dan persegi. Pipi bisa naik di atas rahang atas dan melon terlihat rata." ,
        size: "Panjang saat lahir: 2-2.5m, Panjang dewasa: 4.7m, Berat dewasa: 1033 Kg" ,
        colour_pattern: "Abu-abu hingga abu-abu kecoklatan dengan jaringan parut putih oleh pemotong kue dan tanda penggaruk." ,
        dorsal_fin: "Sirip punggung kecil 2/3 dari ujung mimbar" ,
        teeth_count: "Sepasang taring keluar dari mulutnya." ,
        baleen_plate: null,
        throat_grooves: "Sepasang alur tenggorokan hadir" ,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan dalam lepas pantai 200m atau lebih" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Physeter makrosefalus" ,
        image_path: "Sperm-Whale" ,
        local_name: "paus sperma" ,
        IUCN_status: "VU" ,
        description: "Cetacea bergigi terbesar, tubuhnya besar dengan kerutan. Kepala membentuk 1/3 dari panjang tubuh dan terlihat persegi dari samping. Rahang bawah sangat sempit dibandingkan dengan rahang atas dan memiliki gigi. Rahang atas tidak memiliki gigi. Sebuah lubang sembur berbentuk s ditempatkan sedikit di sebelah kiri kepala/ Siripnya pendek dan berbentuk spatula. Fluke lebar dengan trailing edge lurus dan memiliki banyak takik. Pukulannya lebat dan miring ke depan ke kiri." ,
        size: "Panjang saat lahir: 35-45m, Panjang dewasa: 12.5-19.2m, Berat dewasa: 57000 Kg" ,
        colour_pattern: "Hitam sampai abu-abu kecoklatan" ,
        dorsal_fin: "Sirip punggung menonjol rendah" ,
        teeth_count: "Ada 18-26 pasang gigi di rahang bawah." ,
        baleen_plate: null,
        throat_grooves: "2-10 alur tenggorokan pendek" ,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di dekat lereng benua, di perairan lebih dalam dari 1000m, dan ngarai bawah laut dekat pantai" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Kogia sima" ,
        image_path: "Dwarf-Sperm-Whale" ,
        local_name: "Paus Sperma Kerdil" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh yang kuat dengan kepala seperti hiu dan rahang bawah kecil yang sempit. Lubang sembur terletak sekitar > 10% dari ujung mimbar. Ada tanda di belakang mata yang terlihat seperti celah insang palsu dan sirip kecil ditempatkan dekat dengan kepala." ,
        size: "Panjang saat lahir: 1m, Panjang dewasa: 2.5-2.7m, Berat dewasa: 272 Kg" ,
        colour_pattern: "Abu-abu tua hingga hitam kecoklatan di sisi atas. Tanda di belakang mata yang terlihat seperti celah insang palsu." ,
        dorsal_fin: "Sirip punggung falcate yang tinggi di tengah punggung" ,
        teeth_count: "Rahang bawah memiliki 7-12 pasang gigi; rahang atas terkadang memiliki 3 pasang gigi" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan lepas pantai" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Kogia breviceps" ,
        image_path: "Pygmy-Sperm-Whale" ,
        local_name: "Paus Sperma Pygmy" ,
        IUCN_status: "LC" ,
        description: "tubuh yang kuat; tanda di belakang mata yang terlihat seperti celah insang palsu; kepala seperti hiu; rahang bawah kecil dan sempit; sirip kecil lebih dekat ke kepala; ada punuk kecil di antara lubang sembur dan sirip punggung; lubang sembur terletak >10% dari ujung mimbar." ,
        size: "Panjang saat lahir: 1.2m, Panjang dewasa: 2.7-3.9m, Berat dewasa: 450 Kg" ,
        colour_pattern: "Abu-abu tua hingga hitam kecoklatan di sisi atas. Tanda di belakang mata yang terlihat seperti celah insang palsu." ,
        dorsal_fin: "Sirip punggung kecil melengkung tepat di belakang tengah punggung" ,
        teeth_count: "Rahang bawah memiliki 10-16 pasang gigi" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di lereng benua dan di perairan yang lebih dalam Tidak biasa seperti paus sperma kerdil" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Orcaella brevirostris" ,
        image_path: "Irrawaddy-Dolphin" ,
        local_name: "Lumba-lumba Irrawaddy" ,
        IUCN_status: "EN" ,
        description: "Memiliki moncong bulat tanpa paruh yang menonjol. Siripnya besar dan berbentuk dayung serta terdapat lipatan leher pada orang dewasa." ,
        size: "Panjang saat lahir: 1m, Panjang dewasa: 2.5m, Berat dewasa: 130Kg" ,
        colour_pattern: "abu-abu baja" ,
        dorsal_fin: "Kenop seperti sirip punggung tepat di belakang titik tengah tubuh" ,
        teeth_count: "Rahang atas 8-19 pasang gigi, Rahang bawah 13-14 pasang gigi" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan pantai, laguna, muara dan sungai Distribusi saat ini di India termasuk laguna Chilika, perairan pesisir Orissa utara dan Benggala Barat termasuk Bhitarkanika dan Sundarbans" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Globicephala macrorhynchus" ,
        image_path: "Short-Finned-Pilot-Whale" ,
        local_name: "Paus Pilot bersirip pendek" ,
        IUCN_status: "LC" ,
        description: "Salah satu Ikan Hitam, Paus pilot memiliki sirip punggung menonjol yang ditempatkan di bagian depan tubuh. Moncongnya membulat dengan kepala bulat hampir persegi pada orang dewasa. Siripnya panjang, berbentuk sabit dan meruncing. Jantan jauh lebih besar daripada betina dengan lunas post anal yang menonjol dan sirip falcate lebih banyak dengan alas yang lebih lebar." ,
        size: "Panjang saat lahir: 1.4-1.9m, Panjang dewasa: 5.5-7.2m, Berat dewasa: 3600 Kg" ,
        colour_pattern: "Hitam sampai abu-abu kecoklatan. Ini memiliki patch cahaya berbentuk jangkar pada catur dan dua dua garis-garis cahaya dari dasar sirip punggung di sekitar lubang pukulan jatuh ke mata. Pola pelana berwarna terang terdapat di belakang sirip punggung." ,
        dorsal_fin: "Pola pelana berwarna terang di belakang sirip punggung; sirip punggung besar membulat, rendah dan tepat di depan titik tengah punggung" ,
        teeth_count: "Setiap rahang memiliki 7-9 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan lepas pantai yang dalam dan di sekitar pulau-pulau samudera di mana perairan dekat pantai berada dalam" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Orcinus orca" ,
        image_path: "Killer-Whale" ,
        local_name: "Paus pembunuh" ,
        IUCN_status: "DD" ,
        description: "Lumba-lumba terbesar memiliki tubuh yang kuat, moncong tumpul tanpa paruh yang menonjol dan sirip punggung yang tinggi." ,
        size: "Panjang saat lahir: 2.1-2.6m, Panjang dewasa: 8.5-9.8m, Berat dewasa: 7500-10000 Kg" ,
        colour_pattern: "Pola warna hitam-putih mudah dikenali dengan sadel berwarna terang di belakang sirip punggung." ,
        dorsal_fin: "Mudah dikenali dari sirip punggung tegak segitiga yang sangat besar (sirip punggung jantan tingginya lebih dari 2m; betina memiliki sirip melengkung setinggi 09m)" ,
        teeth_count: "Setiap rahang memiliki 10-14 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Spesies kosmopolitan biasanya terlihat di dekat pantai dan lepas pantai" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Pseudorca crassidens" ,
        image_path: "False-Killer-Whale" ,
        local_name: "Paus Pembunuh Palsu" ,
        IUCN_status: "NT" ,
        description: "Memiliki tubuh panjang ramping dengan moncong membulat dan melon yang landai. Paruhnya tidak menonjol. Siripnya panjang dengan sedikit punuk di tepi depan yang memberi mereka bentuk-S." ,
        size: "Panjang saat lahir: 1.5-2.1m, Panjang dewasa: 5-6m, Berat dewasa: 2000 Kg" ,
        colour_pattern: "Hitam hingga hitam keabu-abuan dengan bercak abu-abu muda di dada dan perut. Jubah yang sangat samar meruncing ke lunas." ,
        dorsal_fin: "Sirip punggung tinggi, melengkung dengan ujung membulat, di tengah punggung" ,
        teeth_count: "Setiap rahang memiliki 7-12 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan lepas pantai yang dalam dan di sekitar pulau-pulau samudera di mana perairan dekat pantai berada dalam" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Feresa attenuata" ,
        image_path: "Pygmy-Killer-Whale" ,
        local_name: "Paus Pembunuh Pygmy" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh yang panjang, kokoh sebelum sirip punggung dan ramping setelahnya. Moncongnya dibulatkan dengan melon miring. Paruhnya tidak menonjol. Siripnya panjang dengan ujung membulat." ,
        size: "Panjang saat lahir: 80cm, Panjang dewasa: 2.6m, Berat dewasa: 225 Kg" ,
        colour_pattern: "Hitam sampai hitam keabu-abuan. Bibir dan ujung paruh berwarna putih. Jubah abu-abu muda yang mencelupkan tepat di bawah sirip punggung menonjol." ,
        dorsal_fin: "Sirip punggungnya tinggi, melengkung ke atas dengan sudut rendah di titik tengah punggung" ,
        teeth_count: "Rahang atas 8-11 pasang gigi dan Rahang bawah 11-13 pasang" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan lepas pantai yang dalam dan di sekitar pulau-pulau samudera di mana perairan dekat pantai berada dalam" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Peponocephala electra" ,
        image_path: "Melon-Headed-Whale" ,
        local_name: "Paus kepala melon" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh ramping panjang dan moncong bulat dengan buah melon. Ada sedikit tanda paruh. Siripnya panjang, runcing dan berbentuk sabit." ,
        size: "Panjang saat lahir: 1m, Panjang dewasa: 2.6m, Berat dewasa: 275 Kg" ,
        colour_pattern: "Berwarna hitam keabu-abuan dengan bibir dan ujung paruh berwarna putih. Jubah abu-abu muda yang mencelupkan (lebih dalam daripada paus pembunuh Pygmy) tepat di bawah sirip punggung terlihat jelas. Patch urinogenital yang lebih ringan." ,
        dorsal_fin: "Sirip punggung tinggi, melengkung di titik tengah punggung" ,
        teeth_count: "Setiap rahang memiliki 20-25 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan lepas pantai yang dalam dan di sekitar pulau-pulau samudera di mana perairan dekat pantai berada dalam" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Grampus griseus" ,
        image_path: "Risso's-Dolphin" ,
        local_name: "Lumba-lumba Risso" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh yang kokoh dengan kepala tumpul dan garis mulut yang miring ke atas. Melon lebih persegi daripada bulat. Siripnya panjang dan runcing. Stok ekor sangat ramping dibandingkan dengan bagian depan tubuh." ,
        size: "Panjang saat lahir: 1-1.5m, Panjang dewasa: 3.8m, Berat dewasa: 500 Kg" ,
        colour_pattern: "Putih keabu-abuan, dengan sebagian besar tubuh penuh bekas luka akibat goresan." ,
        dorsal_fin: "Sirip punggung tinggi, ramping, tegak di titik tengah punggung" ,
        teeth_count: "Rahang bawah memiliki 2-7 pasang gigi dan rahang atas memiliki 1 pasang gigi atau tidak sama sekali; gigi biasanya selalu aus." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di lereng kontinental dan di daerah yang lebih dalam dari paparan terluar" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Steno bredanensis" ,
        image_path: "Rough-Toothed-Dolphin" ,
        local_name: "Lumba-lumba bergigi kasar" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh yang kuat dengan kepala kerucut yang runcing dan melon yang landai tanpa lipatan. Paruhnya panjang dan siripnya besar dan runcing." ,
        size: "Panjang saat lahir: 1m, Panjang dewasa: 2.65m, Berat dewasa: 155 Kg" ,
        colour_pattern: "Hitam keabu-abuan di atas, perut merah muda dan jubah abu-abu lebih terang di sisi yang mencelupkan di bawah sirip punggung. Perut, bibir dan rahang bawah berbintik putih dan terdapat penutup mata berwarna gelap." ,
        dorsal_fin: "Sirip punggung tinggi, ramping, tegak di tengah punggung; paruh panjang" ,
        teeth_count: "Setiap rahang memiliki 19-28 pasang gigi dengan tepi berkerut pada gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan laut dalam Sangat jarang di perairan India" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Sousa plumbea" ,
        image_path: "Indian-Ocean-Humpback-Dolphin" ,
        local_name: "Lumba-lumba Bungkuk Samudera Hindia" ,
        IUCN_status: "EN" ,
        description: "Tubuh yang kokoh, dengan paruh kayu yang sedang. Sirip punggung ditempatkan di titik tengah punggung, di punuk, dan itulah namanya. Ada melon bulat lipatan yang berbeda dan sirip besar dan cacing dengan ujung membulat. Orang dewasa memiliki punuk yang lebih besar, khususnya pada pria." ,
        size: "Panjang saat lahir: 1m, Panjang dewasa: 2.6-2.8m, Berat dewasa: 280 Kg" ,
        colour_pattern: "Hitam keabu-abuan di atas, perut merah muda. Perut, bibir, dan rahang bawah lebih terang, bibir dan rahang bawah, dan belang-belang merah muda. Ada penutup mata berwarna gelap." ,
        dorsal_fin: "Sirip punggung pendek dan runcing duduk di punuk besar tepat di depan titik tengah tubuh" ,
        teeth_count: "Rahang atas memiliki 33-39 pasang gigi dan rahang bawah memiliki 31-37 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Ditemukan di dekat pantai perairan dangkal dengan kedalaman kurang dari 30 m, dekat dengan muara sungai dan di muara Spesies yang paling umum di sepanjang pantai barat India" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Sousa chinensis" ,
        image_path: "Indo-Pacific-Humpback-Dolphin" ,
        local_name: "Lumba-lumba Bungkuk Indo-Pasifik" ,
        IUCN_status: "VU" ,
        description: "Tubuh yang kokoh, dengan paruh kayu yang sedang. Ada melon bulat dengan lipatan yang berbeda. Sirip punggung ditempatkan di titik tengah punggung, di punuk, dan itulah namanya. Punuk yang landai di bawah sirip tidak diucapkan seperti pada S plumbea. Sirip berada di titik tengah punggung. Sirip dan cacing dengan ujung membulat. Orang dewasa memiliki punuk yang lebih besar, khususnya pada jantan (jantan dewasa memiliki berat tiga kali lebih banyak daripada betina dewasa)." ,
        size: "Panjang saat lahir: 1m, Panjang dewasa: 2.7m, Berat dewasa: 240 Kg" ,
        colour_pattern: "Merah muda keabu-abuan dengan lebih banyak merah muda di sisi, di sekitar mulut dan perut merah muda." ,
        dorsal_fin: "Sirip punggungnya pendek" ,
        teeth_count: "Rahang atas memiliki 32-38 pasang gigi dan rahang bawah memiliki 29-38 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Ditemukan di pantai timur India Area tumpang tindih antara S plumbea dan chinensis diperkirakan berada di tenggara India Ditemukan di dekat pantai perairan dangkal dengan kedalaman kurang dari 30 m, dekat dengan muara sungai dan di muara" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Tursiops aduncus" ,
        image_path: "Indo-Pacific-Bottlenose-Dolphin" ,
        local_name: "Lumba-lumba hidung botol Indo-Pasifik" ,
        IUCN_status: "NT" ,
        description: "Memiliki tubuh yang kuat dengan kepala bulat dan dahi yang landai. Paruhnya panjang dengan rahang bawah sedikit lebih panjang dari rahang atas. Ada lipatan yang menonjol. Siripnya kecil, runcing." ,
        size: "Panjang saat lahir: 85-112cm, Panjang dewasa: 2.7m, Berat dewasa: 230 Kg" ,
        colour_pattern: "Abu-abu di bagian atas dengan jubah abu-abu lebih terang di sisinya dan berkobar naik ke arah sirip punggung. Betis memiliki perut merah muda sementara yang sama terlihat hitam pada orang dewasa." ,
        dorsal_fin: "Sirip punggungnya tinggi dengan pangkal yang lebar" ,
        teeth_count: "Setiap rahang memiliki 21-29 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Ditemukan di perairan dekat pantai Perairan India mungkin juga memiliki Tursiops truncatus (lumba-lumba hidung botol yang umum) ditemukan di perairan tetapi di perairan yang lebih dalam T truncatus memiliki paruh yang lebih pendek, tubuh yang lebih kuat, sirip yang lebih melengkung, dan tidak ada bintik-bintik di perut" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Stenella attenuata" ,
        image_path: "Pan-Tropical-Spotted-Dolphin" ,
        local_name: "Lumba-lumba tutul pan-tropis" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh ramping ramping dengan melon menonjol dengan lipatan. Sirip punggung tinggi, ramping, membulat di ujung di tengah punggung. Paruhnya cukup panjang, siripnya ramping dan runcing." ,
        size: "Panjang saat lahir: 90cm, Panjang dewasa: 2.4-2.6m, Berat dewasa: 119 Kg" ,
        colour_pattern: "Lumba-lumba tutul pantropis berwarna abu-abu secara keseluruhan, lebih gelap di atas dan di sisi atas, dan lebih terang di perut dan sisi bawah. Tubuh biasanya terlihat, meskipun bercak bervariasi di setiap daerah, dengan bintik-bintik putih di atas dan bintik-bintik gelap di bawah. Bercak meningkat seiring bertambahnya usia dan wilayah. Lumba-lumba tutul yang baru lahir tidak berbintik, memiliki punggung abu-abu gelap dengan tepi lembut dan perut terang. Di laut, kehadiran unik dari kekang yang ditandai, jubah gelap seragam di sisi punggung, dan kehadiran garis sirip gelap membantu dalam mengidentifikasi spesies." ,
        dorsal_fin: " Sirip punggung yang tinggi dan berbentuk seperti falcate yang ditempatkan di tengah" ,
        teeth_count: "Setiap rahang memiliki 35-40 gigi runcing kecil." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Lumba-lumba tutul pan-tropis ditemukan di lautan tropis dengan suhu permukaan yang hangat, baik di daerah pesisir maupun lepas pantai. Bentuk pantai umumnya lebih besar dan lebih banyak berbintik daripada yang hidup di lepas pantai." ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Stenella longirostris" ,
        image_path: "Spinner-Dolphin" ,
        local_name: "Lumba-lumba pemintal" ,
        IUCN_status: "DD" ,
        description: "Memiliki tubuh yang sangat ramping dengan dahi yang landai. Ada lipatan dan paruhnya sangat panjang. Siripnya ramping dan runcing." ,
        size: "Panjang saat lahir: 75-80cm, Panjang dewasa: 1.5-2.3m, Berat dewasa: 82 Kg" ,
        colour_pattern: "Hitam keabu-abuan di atas, pita abu-abu lebih terang di sepanjang sisi dan perut putih (pola tripartit). Garis mata gelap dari mata ke lipatan dan mata ke sirip. Paruh atas berwarna gelap dan paruh bawah berwarna putih dengan ujung hitam hingga paruh atas." ,
        dorsal_fin: "Sirip punggung tinggi, ramping, tegak di titik tengah punggung" ,
        teeth_count: "Setiap rahang memiliki 40-62 pasang gigi (lumba-lumba pemintal kerdil memiliki 41-52 pasang gigi di setiap rahang)" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Ditemukan di perairan lepas pantai yang dalam dan di sekitar pulau-pulau samudera di mana perairan dekat pantai berada dalam" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Stenella coeruleoalba" ,
        image_path: "Striped-Dolphin" ,
        local_name: "Lumba-lumba bergaris" ,
        IUCN_status: "LC" ,
        description: "Tubuhnya tidak ramping seperti Stenella lainnya. Mereka memiliki dahi yang landai dan paruh yang cukup panjang. Siripnya ramping dan runcing dan ada lipatan." ,
        size: "Panjang saat lahir: 93-100cn, Panjang dewasa: 2.56m, Berat dewasa: 155 Kg" ,
        colour_pattern: "Hitam keabu-abuan di atas dengan jubah gelap. Abu-abu lebih terang di bagian samping dengan nyala ke arah depan sirip punggung. Garis gelap membentang dari mata ke anus dan mata ke sirip Paruh atas berwarna gelap dan paruh bawah berwarna putih dengan ujung hitam" ,
        dorsal_fin: "Sirip punggung berbentuk segitiga dengan dasar lebar di tengah punggung" ,
        teeth_count: "Setiap rahang memiliki 40-55 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan dalam samudera" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Delphinus capensis tropicalis" ,
        image_path: "Indo-Pacific-Common-Dolphin" ,
        local_name: "Lumba-lumba umum Indo-Pasifik" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh yang sangat ramping dengan dahi yang landai dan lipatan yang menonjol. Mereka memiliki paruh yang sangat panjang dan siripnya panjang, ramping dan runcing." ,
        size: "Panjang saat lahir: 80-100cm, Panjang dewasa: 2.6m, Berat dewasa: 235 Kg" ,
        colour_pattern: "Hitam keabu-abuan di bagian atas, perut putih lebih terang dengan pola kaca jam berbentuk v yang menonjol di bawah sirip punggung dan api kuning di atas sirip." ,
        dorsal_fin: "Sirip punggungnya tinggi, ramping, melengkung dan berada di tengah punggung" ,
        teeth_count: "Rahang atas memiliki 54-67 pasang gigi dan rahang bawah memiliki 52-64 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Tidak dikenal" ,
        habitat_preferance: "Ditemukan di perairan yang lebih dalam di landas kontinen dan di lereng, terkadang di perairan dalam dekat pantai" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Lagenodelphis hosei" ,
        image_path: "Fraser's-Dolphin" ,
        local_name: "Lumba-lumba Fraser" ,
        IUCN_status: "LC" ,
        description: "Memiliki tubuh yang sangat kekar dengan dahi yang landai, dengan lipatan yang menonjol. antara melon dan paruh. Paruhnya sendiri pendek dan gemuk Siripnya panjang dan runcing di ujungnya." ,
        size: "Panjang saat lahir: 1-1.1m, Panjang dewasa: 2.6-2.7m, Berat dewasa: 210 Kg" ,
        colour_pattern: "Keabu-abuan di atas dengan perut merah muda dan pita abu-abu lebih terang membentang dari wajah ke anus. Garis abu-abu terlihat dari tengah rahang bawah hingga sirip sementara garis gelap terlihat dari puncak melon hingga ujung rahang atas. Ujung paruhnya gelap." ,
        dorsal_fin: "Sirip punggung pendek, berbentuk segitiga dan tegak di tengah punggung" ,
        teeth_count: "Setiap rahang memiliki 38-44 pasang gigi." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "tidak diketahui" ,
        habitat_preferance: "Spesies laut ditemukan di perairan lepas pantai dalam" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Neophocaena phocaenoides" ,
        image_path: "Indo-Pacific-Finless-Porpoise" ,
        local_name: "Lumba-lumba tanpa sirip Indo-Pasifik" ,
        IUCN_status: "VU" ,
        description: "Memiliki tubuh berbentuk torpedo dengan kepala bulat dan moncong membulat. Tidak ada paruh. Siripnya panjang dan melengkung. Kebetulan itu berlekuk." ,
        size: "Panjang saat lahir: 75-85cm, Panjang dewasa: 1.5m, Berat dewasa: 60 Kg" ,
        colour_pattern: "Abu-abu tua sampai abu-abu coklat dengan tambalan tuberkel di bagian belakang dengan deretan 10-25 tuberkel. Tidak ada sirip punggung." ,
        dorsal_fin: "Sirip punggung tidak ada" ,
        teeth_count: "Gigi berbentuk sekop dengan 15-22 pasang gigi di setiap rahang" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Ditemukan di sepanjang pantai India termasuk Sundarbans, di perairan dekat pantai dan di muara" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Platanista gangetika" ,
        image_path: "South-Asian-River-Dolphin" ,
        local_name: "Lumba-lumba sungai Asia Selatan" ,
        IUCN_status: "EN" ,
        description: "Lumba-lumba Sungai Asia Selatan memiliki tubuh kekar dan paruh panjang ramping dengan ujung rata. Paruhnya lebih panjang pada wanita dan relatif lebih pendek pada pria. Terdapat lipatan yang menonjol antara paruh dan melon, dengan tonjolan pada melon. Sebuah celah tunggal menandakan lubang sembur. Matanya seperti lubang kecil dan cacingnya lebar dengan tepi bagian dalam yang cekung dan lekukan yang menonjol. Sirip braod dengan ujung distal persegi." ,
        size: "Panjang saat lahir: 70-90cm, Panjang dewasa: 1.6-2.6m, Berat dewasa: 85 Kg" ,
        colour_pattern: "Bagian atas dan belakang berwarna coklat muda hingga abu-abu kecoklatan sedangkan bagian bawah berwarna terang" ,
        dorsal_fin: "Sirip punggung rendah, kecil, segitiga, lebar dan sekitar 2/3 dari ujung mimbar" ,
        teeth_count: "Rahang atas memiliki 26-39 pasang gigi dan rahang bawah memiliki 26-35 pasang gigi" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "Populasi penduduk" ,
        habitat_preferance: "Ditemukan di sungai Indus, Gangga, Brahmaputra, Meghna dan Karnaphuli Sangu dan anak-anak sungainya. P.g.minor ditemukan di drainase Indus di Pakistan dan sungai Beas di India. Pg gangetica ditemukan di sisa rentang distribusi spesies." ,
        type: "Marine Mammals" ,
    },
]

data.sort((a, b) => a.scientific_name.localeCompare(b.scientific_name))

const d: IDatabaseEntry[] = data.map((e,i) => {
    return {
        id: i.toString(),
        ...e
    }
})

export default d