import { IDatabaseEntry } from '../../src/Interface/Interface'

const data: any[] = [
    {   
        scientific_name: "ඩුගොං ඩුගොං" ,
        image_path: "Dugong" ,
        local_name: "ඩුගොං" ,
        IUCN_status: "VU" ,
        description: "සිලින්ඩරාකාර සහ නලයක් වැනි හිසක් මුහුදු තණකොළ කෑම සඳහා පහළට නැමී ඇත. කඳ ඉණ ප්" ,
        size: "උපතේදී දිග: 1-1.3m, වැඩිහිටි දිග: 2.5-2.7m, වැඩිහිටි බර: 570 Kg" ,
        colour_pattern: "අපිරිසිදු දුඹුරු අළු" ,
        dorsal_fin: "ඔවුන්ට පෘෂ්ඨීය වරල් නොමැත" ,
        teeth_count: "පිරිමි සතුන් තුළ දළ වශයෙන් පිපිරෙන ඉහළ හකු මත එක් කෘන්තකයක් සහිත හකු වල එක් එක් හතරේ දත් හයක්" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "Dugongs ජීවත් වන්නේ මුහුදු තෘණ ඇඳන් ඇති නොගැඹුරු, ආරක්ෂිත වෙරළබඩ ජලයේ ඉන්දියාවේ වත්මන් ව්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Megaptera novaeangliae" ,
        image_path: "Humpback-Whale" ,
        local_name: "හම්ප්බැක් තල්මසා" ,
        IUCN_status: "LC" ,
        description: "අනෙක් rorquals ට වඩා ශක්තිමත් ශරීරයක්. හිස මුදුන සමතලා කර ඇති අතර රිජ් එකක් නොමැතිව මස් මිටි ගණනාවකින් ආවරණය වී ඇත. යටි හකු කෙළවරේ වටකුරු නෙරා ඇත. ඉහළින්, හිස පුළුල් හා වටකුරු ය. උගුර කට්ට ගණන 14 සිට 35 දක්වා වන අතර එය නහය දක්වා විහිදේ. Flippers ඉතා දිගු වන අතර, මුළු සිරුරේ දිග ප්රමාණයෙන් තුනෙන් එකක් පමණ වේ. ඒවා මිටි හෝ ගැටිති වලින් කපා ඇත. ඔවුන් රංචු ගැසෙන කබොල සහ සොලවන මසුන් පෝෂණය කරයි." ,
        size: "උපතේදී දිග: 4.3m, වැඩිහිටි දිග: 11-17m, වැඩිහිටි බර: 40000 Kg" ,
        colour_pattern: "කළු හෝ අළු, උගුරේ සහ උදරයේ සුදු කලාපයක් ඇත. ෆ්ලිපර්ස් යටින් සුදු ය, සමහර විට ඉහළින් ද ඇත." ,
        dorsal_fin: "පෘෂ්ඨීය වරල පිහිටා ඇත්තේ වලිග තුණ්ඩයේ සිට සිරුරේ දිගෙන් තුනෙන් එකකටත් වඩා අඩු ප්" ,
        teeth_count: null,
        baleen_plate: "යුගල 350-370" ,
        throat_grooves: "උගුර කට්ට ගණන 14 සිට 35 දක්වා වන අතර එය නහය දක්වා විහිදේ" ,
        seasonal_movement: "අරාබි මුහුදේ" ,
        habitat_preferance: " වෙරළබඩ සහ මහාද්වීපික රාක්ක දාර ජලයේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Balaenoptera මස්කියුලස්" ,
        image_path: "Blue-Whale" ,
        local_name: "නිල් තල්මසා" ,
        IUCN_status: "EN" ,
        description: "පුළුල් 'U' හැඩැති හිසක් ඇත්තේ තනි මධ්" ,
        size: "උපතේදී දිග: 7-8m, වැඩිහිටි දිග: 25-29m, වැඩිහිටි බර: 72000-135000 Kg" ,
        colour_pattern: "මෝටල් සහිත නිල් අළු." ,
        dorsal_fin: "ඉතා කුඩා පෘෂ්ඨීය වරල් රොස්ට්" ,
        teeth_count: null,
        baleen_plate: "baleen යුගල 260-400" ,
        throat_grooves: "70-118 (බොහෝ විට 90-95) කශේරුකා ප්ලීස් නහය දක්වාම" ,
        seasonal_movement: "අරාබි මුහුද - බෙංගාල බොක්ක" ,
        habitat_preferance: "විවෘත-සාගර විශේෂ, පෝෂණය සඳහා වෙරළට ආසන්නව දක්නට ලැබේ. අරාබි මුහුදේ පිග්මි බ්ලූ තල්මසා ද සිටී." ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Balaenoptera edeni" ,
        image_path: "Bryde’s-Whale" ,
        local_name: "බ්රයිඩ්ගේ තල්මසා" ,
        IUCN_status: "LC" ,
        description: "සෘජු පසුපස දාර සහිත පුළුල් තලයක් සහිත සිනිඳු සිරුරක් ඇත. රෝස්ට්" ,
        size: "උපතේදී දිග: 4m, වැඩිහිටි දිග: 15-16.5m, වැඩිහිටි බර: 40000 Kg" ,
        colour_pattern: "තද අළු" ,
        dorsal_fin: " රෝස්ට්" ,
        teeth_count: null,
        baleen_plate: "baleen යුගල 250-370" ,
        throat_grooves: "40- 70 (අරාබි මුහුද සඳහා 42-54) නහය දක්වා හෝ ඉන් ඔබ්බට උදරීය ප්ලීස්" ,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "මුහුදු වෙරළේ සහ වෙරළ ආසන්නයේ හමු විය" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Balaenoptera omurai" ,
        image_path: "Omura's-Whale" ,
        local_name: "ඔමුරාගේ තල්මසා" ,
        IUCN_status: "DD" ,
        description: "තනි කැපී පෙනෙන මධ්" ,
        size: "උපතේදී දිග: 3.5-4m, වැඩිහිටි දිග: 9.6-11.5m, වැඩිහිටි බර: 20000 Kg" ,
        colour_pattern: "අඳුරු පෘෂ්ඨීය සහ සැහැල්ලු කශේරුකා ශරීරය සමඟ ද්වි-වර්ණ ශරීර වර්ණ ගැන්වීම." ,
        dorsal_fin: "ඉහළ විකෘති වූ සහ පසුපසට අතුල්ලන ලද පෘෂ්ඨීය වරලයක් මතුපිටින් පිඹින සිදුරක් සහිතව දිස්වේ" ,
        teeth_count: null,
        baleen_plate: "කෙටි සහ පුළුල් baleen යුගල 180-210, ඉදිරිපස කහ සුදු සහ පිටුපස කළු" ,
        throat_grooves: "80-90 කශේරුකා ප්ලීස් නහයෙන් ඔබ්බට විහිදේ" ,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මීටර් 202 ක් දක්වා නොගැඹුරු මහාද්වීපික රාක්කවල ආසන්න වෙරළේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "මෙසොප්ලොඩොන් පැසිෆිකස්" ,
        image_path: "Longman's-Beaked-Whale" ,
        local_name: "ලෝන්ග්මන්ගේ හොට සහිත තල්මසා" ,
        IUCN_status: "DD" ,
        description: "කැපී පෙනෙන හොටක් සහිත සිහින් හැඩැති ශරීරයක් සහ හොට සහ කොමඩු අතර රැල්ලක් සහිත නෙරා ගිය නළලක් ඇත. රේඛීය රේක් ලකුණු නොමැති අතර flukes හට නොච් එකක් නොමැත. flippers කුඩා මොට වේ. බ්ලෝහෝල් හි කෙළවර ඉදිරිපස දෙසට යොමු කරයි." ,
        size: "උපතේදී දිග: 2.9m, වැඩිහිටි දිග: 6.5m, වැඩිහිටි බර: Unknown" ,
        colour_pattern: "පෘෂ්ඨීය ශරීරය අළු සිට දුඹුරු අළු පැහැයක් ගන්නා අතර පැති, යටි සහ හිස ලා පැහැති වේ. බොහෝ විට, කුකී කටර් මෝරුන්ගේ සුදු කැළැල් ශරීරයේ දක්නට ලැබේ." ,
        dorsal_fin: "පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "විදුරුමස් වල තනි දත් යුගලයක් සහ පිටත නොපෙනේ" ,
        baleen_plate: null,
        throat_grooves: "V-හැඩයේ d උගුරේ වලක් පවතී" ,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "ගැඹුරු සාගරවල වෙරළ තීරයේ හමු විය" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "මෙසොප්ලොඩොන් හොටවුලා" ,
        image_path: "Deraniyagala’s-Beaked-Whale" ,
        local_name: "දැරණියගලගේ හොට තල්මසා" ,
        IUCN_status: "DD" ,
        description: "ස්පින්ඩල් හැඩැති ශරීරයක් සහ කුඩා පටු flippers ඇත. මුඛ රේඛාව එහි දිග දිගේ වක්" ,
        size: "උපතේදී දිග: 2m, වැඩිහිටි දිග: 3.9-4.8m, වැඩිහිටි බර: Unknown" ,
        colour_pattern: "සුදු කැළැල් සහිත තද අළු. යටි හකු කෙළවර සුදු ය." ,
        dorsal_fin: "කුඩා පෘෂ්ඨීය වරල් රොස්ට්" ,
        teeth_count: "ඉදිරියට යොමු වන කේතුකාකාර ඇත් දළ යුගලයක් පුපුරා යන්නේ වැඩිහිටි පිරිමින්ගේ යටි හකු ප්" ,
        baleen_plate: null,
        throat_grooves: " V-හැඩැති උගුරේ වලක් පවතී" ,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "බෙදා හැරීම නොදන්නා නමුත් ගැඹුරු ජලයේ මුහුදේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Mesoplodon ginkgodens" ,
        image_path: "Ginkgo-Toothed-Beaked-Whale" ,
        local_name: "Ginkgo-Toothed Beaked Whale" ,
        IUCN_status: "DD" ,
        description: "කුඩා පටු flippers සහිත ස්පින්ඩල් හැඩැති ශරීරයක් ඇත. පිරිමින්ගේ ආරුක්කු මුඛ රේඛාවක් සහිත කුඩා හිසක්." ,
        size: "උපතේදී දිග: 2-2.5m, වැඩිහිටි දිග: 5.3m, වැඩිහිටි බර: Unknown" ,
        colour_pattern: "රෝස්ට්" ,
        dorsal_fin: "කුඩා පෘෂ්ඨීය වරල් රොස්ට්" ,
        teeth_count: "වැඩිහිටි පිරිමින් තුළ පමණක් පිපිරෙන පහළ හකු මැද පළල්, පැතලි s හැඩැති ඇත් දළ ඇත." ,
        baleen_plate: null,
        throat_grooves: "උගුර කට්ට යුගලයක් පවතී" ,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "බෙදා හැරීම නොදන්නා; මුහුදේ ගැඹුරු ජලයේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Ziphius cavirostris" ,
        image_path: "Cuvier's-Beaked-Whale" ,
        local_name: "කූවියර්ගේ හොට සහිත තල්මසා" ,
        IUCN_status: "LC" ,
        description: "කෙටි හොටක් සහ කුඩා පටු flippers සහිත ස්පින්ඩල් හැඩැති ශරීරයක් ඇත. සිනිඳු බෑවුම් නළලක් (පිරිමි පිරිමි කොමඩු හැඩය පෙන්වයි) එහි දිග දිගේ වක්" ,
        size: "උපතේදී දිග: 2.7m, වැඩිහිටි දිග: 6-7m, වැඩිහිටි බර: 3000 Kg" ,
        colour_pattern: "අළු සිට ලා මලකඩ දුඹුරු දක්වා කුකී කටර් කැළැල් සහ රේක් ලකුණු සමඟින්. පිරිමින්ගේ හිසේ සහ පිටේ බොහෝ සුදු පැහැයක් ගනී." ,
        dorsal_fin: "කුඩා පෘෂ්ඨීය වරල් රොස්ට්" ,
        teeth_count: "එක් කේතුකාකාර දත් යුගලයක් පුපුරා යන්නේ වැඩිහිටි පිරිමින්ගේ යටි හකු කෙළවරේ පමණි." ,
        baleen_plate: null,
        throat_grooves: "V-හැඩැති උගුර කට්ට යුගලයක් ඇත" ,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මහාද්වීපික බෑවුම් වලට ආසන්න මුහුදේ සහ ගැඹුරු ජලයේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Mesoplodon densirostris" ,
        image_path: "Blainville's-Beaked-Whale" ,
        local_name: "Blainville's Beaked Whale" ,
        IUCN_status: "LC" ,
        description: "ඉදිරිපස කෙළවරේ එල්ලෙන ක්" ,
        size: "උපතේදී දිග: 2-2.5m, වැඩිහිටි දිග: 4.7m, වැඩිහිටි බර: 1033 Kg" ,
        colour_pattern: "කුකී කටර් සහ රේක් සලකුණු මගින් සුදු කැළැල් සහිත අළු සිට දුඹුරු අළු දක්වා." ,
        dorsal_fin: "කුඩා පෘෂ්ඨීය වරල් රොස්ට්" ,
        teeth_count: "එක දළ යුගලයක් කටින් පිට වෙනවා." ,
        baleen_plate: null,
        throat_grooves: "තනි උගුර කට්ට යුගලයක් පවතී" ,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මීටර් 200 ක් හෝ ඊට වැඩි මුහුදු වෙරළේ ගැඹුරු ජලයේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Physeter macrocephalus" ,
        image_path: "Sperm-Whale" ,
        local_name: "Sperm Whale" ,
        IUCN_status: "VU" ,
        description: "දත් සහිත කැටේසියස් වලින් විශාලතම, ශරීරය රැලි සහිත විශාලයි. හිස සිරුරේ දිගෙන් 1/3ක් වන අතර පැත්තෙන් බැලූ බැල්මට හතරැස් ලෙස පෙනේ. ඉහළ හකුට සාපේක්ෂව පහළ හකු ඉතා පටු වන අතර දත් ඇත. ඉහළ හකුට දත් නැත. තනි s හැඩැති බ්ලෝහෝල් එකක් හිසෙන් මදක් වම් පස තබා ඇත/ ෆ්ලිපර් කෙටි සහ spatula හැඩැති ය. නළය සෘජු පසුපස දාරයක් සහිත පුළුල් වන අතර බොහෝ සටහන් ඇත. පහර පඳුරු සහිත වන අතර වමට ඉදිරියට නැඹුරු වේ." ,
        size: "උපතේදී දිග: 35-45m, වැඩිහිටි දිග: 12.5-19.2m, වැඩිහිටි බර: 57000 Kg" ,
        colour_pattern: "කළු සිට දුඹුරු අළු" ,
        dorsal_fin: "පහත් knobby පෘෂ්ඨීය වරල්" ,
        teeth_count: "පහළ හකු වල දත් යුගල 18-26 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: "2-10 කෙටි උගුර කට්ට" ,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මහාද්වීපික බෑවුම අසල, මීටර් 1000 ට වඩා ගැඹුරු ජලයේ සහ වෙරළට ආසන්න සබ්මැරීන් කැනියන් හමු විය" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "කොගියා සිමා" ,
        image_path: "Dwarf-Sperm-Whale" ,
        local_name: "වාමන ශුක්" ,
        IUCN_status: "LC" ,
        description: "මෝරෙකු වැනි හිසක් සහ කුඩා පටු යටි හකු සමග ශක්තිමත් ශරීරයක් ඇත. බ්ලෝහෝල් පිහිටා ඇත්තේ රෝස්ට්" ,
        size: "උපතේදී දිග: 1m, වැඩිහිටි දිග: 2.5-2.7m, වැඩිහිටි බර: 272 Kg" ,
        colour_pattern: "ඉහළ පැත්තේ තද අළු සිට දුඹුරු කළු. ඇසට පිටුපසින් ව්" ,
        dorsal_fin: "පිටුපස මැද ඇති උස පෘෂ්ඨීය වරල්" ,
        teeth_count: "පහළ හකු දත් යුගල 7-12 ක් ඇත; ඉහළ හකු සමහර විට දත් යුගල 3 ක් ඇත" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මුහුදු වෙරළේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Kogia breviceps" ,
        image_path: "Pygmy-Sperm-Whale" ,
        local_name: "පිග්මි ස්පර්ම් තල්මසා" ,
        IUCN_status: "LC" ,
        description: "ශක්තිමත් ශරීරය; අසත්" ,
        size: "උපතේදී දිග: 1.2m, වැඩිහිටි දිග: 2.7-3.9m, වැඩිහිටි බර: 450 Kg" ,
        colour_pattern: "ඉහළ පැත්තේ තද අළු සිට දුඹුරු කළු. ඇසට පිටුපසින් ව්" ,
        dorsal_fin: "කුඩා වක්" ,
        teeth_count: "පහළ හකු දත් යුගල 10-16 ක් ඇත" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මහාද්වීපික බෑවුමේ සහ ගැඹුරු ජලයේ දක්නට ලැබේ වාමන ශුක්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Orcaella brevorostris" ,
        image_path: "Irrawaddy-Dolphin" ,
        local_name: "Irrawaddy ඩොල්ෆින්" ,
        IUCN_status: "EN" ,
        description: "කැපී පෙනෙන හොටක් නොමැතිව වටකුරු නාසයක් ඇත. flippers විශාල වන අතර පැඩල් හැඩැති අතර වැඩිහිටියන්ගේ ගෙල රැලි ඇත." ,
        size: "උපතේදී දිග: 1m, වැඩිහිටි දිග: 2.5m, වැඩිහිටි බර: 130Kg" ,
        colour_pattern: "වානේ අළු" ,
        dorsal_fin: "සිරුරේ මැද ලක්ෂ්" ,
        teeth_count: "ඉහළ හකු දත් යුගල 8-19, පහළ හකු 13-14 දත් යුගල" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "වෙරළබඩ ජලය, කලපු, මෝය සහ ගංගා වල දක්නට ලැබේ, ඉන්දියාවේ වත්මන් ව්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Globicephala macrorhynchus" ,
        image_path: "Short-Finned-Pilot-Whale" ,
        local_name: "කෙටි වරල් නියමු තල්මසා" ,
        IUCN_status: "LC" ,
        description: "කළු මත්ස්" ,
        size: "උපතේදී දිග: 1.4-1.9m, වැඩිහිටි දිග: 5.5-7.2m, වැඩිහිටි බර: 3600 Kg" ,
        colour_pattern: "කළු සිට දුඹුරු අළු. එහි චෙස් මත නැංගුරම් හැඩැති ආලෝක පැල්ලමක් සහ ඇසට වැටෙන පිහාටු සිදුර වටා පෘෂ්ඨීය වරල් පාමුල සිට ආලෝක ඉරි දෙකක් ඇත. පෘෂ්ඨීය වරල පිටුපස ලා පැහැති සෑදල රටාවක් ඇත." ,
        dorsal_fin: "පෘෂ්ඨීය වරල පිටුපස ලා පැහැති සෑදල රටාවක්; විශාල වටකුරු පෘෂ්ඨීය වරල, පහත් සහ පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "සෑම හකුටම දත් යුගල 7-9 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "ගැඹුරු අක්වෙරළ ජලයේ සහ ආසන්න වෙරළ ජලය ගැඹුරු සාගර දූපත් අවට දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Orcinus orca" ,
        image_path: "Killer-Whale" ,
        local_name: "මිනීමරු තල්මසා" ,
        IUCN_status: "DD" ,
        description: "විශාලතම ඩොල්ෆින් මත්ස්" ,
        size: "උපතේදී දිග: 2.1-2.6m, වැඩිහිටි දිග: 8.5-9.8m, වැඩිහිටි බර: 7500-10000 Kg" ,
        colour_pattern: "පෘෂ්ඨීය වරල පිටුපස ලා පැහැති සෑදලයක් සහිත කළු-සුදු වර්ණ රටා හඳුනා ගැනීම පහසුය." ,
        dorsal_fin: "එහි ඉතා විශාල ත්" ,
        teeth_count: "සෑම හකුකම දත් යුගල 10-14 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "කොස්මොපොලිල්ටන් විශේෂයක් සාමාන්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Pseudorca crassidens" ,
        image_path: "False-Killer-Whale" ,
        local_name: "False Killer Whale" ,
        IUCN_status: "NT" ,
        description: "වටකුරු නහයක් සහ මෘදු බෑවුම් සහිත කොමඩු ගෙඩියක් සහිත දිගු සිහින් සිරුරක් ඇත. හොට කැපී පෙනෙන්නේ නැත. Flippers දිගු වන අතර ප්" ,
        size: "උපතේදී දිග: 1.5-2.1m, වැඩිහිටි දිග: 5-6m, වැඩිහිටි බර: 2000 Kg" ,
        colour_pattern: "පපුවේ සහ බඩේ ලා අළු පැල්ලමක් සහිත කළු සිට අළු කළු. ඉතා දුර්වල තොප්පිය keel වෙත ටපරේ." ,
        dorsal_fin: "පෘෂ්ඨීය වරල උසයි, පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "සෑම හකුකම දත් යුගල 7-12 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "ගැඹුරු අක්වෙරළ ජලයේ සහ ආසන්න වෙරළ ජලය ගැඹුරු සාගර දූපත් අවට දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Feresa attenuata" ,
        image_path: "Pygmy-Killer-Whale" ,
        local_name: "පිග්මි කිලර් තල්මසා" ,
        IUCN_status: "LC" ,
        description: "දිගු ශරීරයක් ඇත, පෘෂ්ඨීය වරලයට පෙර ශක්තිමත් සහ සිහින් පසු. තුණ්ඩය බෑවුම් සහිත කොමඩු ගෙඩියකින් වටකුරු ය. හොට කැපී පෙනෙන්නේ නැත. Flippers වටකුරු ඉඟි සමග දිගු වේ." ,
        size: "උපතේදී දිග: 80cm, වැඩිහිටි දිග: 2.6m, වැඩිහිටි බර: 225 Kg" ,
        colour_pattern: "කළු සිට අළු පැහැති කළු. තොල් සහ හොට ඉඟි සුදු ය. පෘෂ්ඨීය වරලයට යටින් ගිල්වන ලා අළු පැහැති කේප් එකක් කැපී පෙනේ." ,
        dorsal_fin: "පෘෂ්ඨීය වරල උසයි, පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "ඉහළ හකු දත් යුගල 8-11 ක් සහ පහළ හකු යුගල 11-13 කි" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "ගැඹුරු අක්වෙරළ ජලයේ සහ ආසන්න වෙරළ ජලය ගැඹුරු සාගර දූපත් අවට දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "පෙපොනොසෙෆලා ඉලෙක්ට්" ,
        image_path: "Melon-Headed-Whale" ,
        local_name: "කොමඩු හිස සහිත තල්මසා" ,
        IUCN_status: "LC" ,
        description: "දිගු සිහින් සිරුරක් සහ කොමඩු ගෙඩියක් සහිත වටකුරු නාසයක් ඇත. හොටක සුළු ඉඟියක් ඇත. flippers දිගු, උල් සහ දෑකැත්ත හැඩැති ය." ,
        size: "උපතේදී දිග: 1m, වැඩිහිටි දිග: 2.6m, වැඩිහිටි බර: 275 Kg" ,
        colour_pattern: "සුදු පැහැති තොල් සහ හොට ඉඟි සහිත අළු කළු පැහැය. පෘෂ්ඨීය වරලයට යටින් ලා අළු පැහැති තොප්පියක් ගිල්වීම (පිග්මි මිනීමරු තල්මසුන්ට වඩා ගැඹුරින්) කැපී පෙනේ. සැහැල්ලු urinogenital පැච් එකක්." ,
        dorsal_fin: "පෘෂ්ඨීය වරල උසයි, පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "සෑම හකුකම දත් යුගල 20-25 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "ගැඹුරු අක්වෙරළ ජලයේ සහ ආසන්න වෙරළ ජලය ගැඹුරු සාගර දූපත් අවට දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "ග්" ,
        image_path: "Risso's-Dolphin" ,
        local_name: "රිසෝගේ ඩොල්ෆින්" ,
        IUCN_status: "LC" ,
        description: "මොට හිසක් සහ ඉහළට බෑවුම් වන මුඛ රේඛාවක් සහිත ශක්තිමත් ශරීරයක් ඇත. කොමඩු වටයට වඩා හතරැස් ය. Flippers දිගු හා උල් වේ. ශරීරයේ ඉදිරිපස හා සසඳන විට වලිගය ඉතා සිහින් ය." ,
        size: "උපතේදී දිග: 1-1.5m, වැඩිහිටි දිග: 3.8m, වැඩිහිටි බර: 500 Kg" ,
        colour_pattern: "අළු පැහැයට හුරු සුදු පැහැය, සිරුරේ වැඩි කොටසක් රේක් සලකුණු වලින් දැඩි ලෙස කැළැල් ඇත." ,
        dorsal_fin: "පෘෂ්ඨීය වරල උස, සිහින්, පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "පහළ හකුට දත් යුගල 2-7ක් ඇති අතර ඉහළ හකුට දත් යුගල 1ක් හෝ නැත; දත් සාමාන්යයෙන් සෑම විටම නරක් වේ." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මහාද්වීපික බෑවුමෙන් සහ පිටත තට්ටුවේ ගැඹුරු ප්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "ස්ටෙනෝ බ්රෙඩනෙන්සිස්" ,
        image_path: "Rough-Toothed-Dolphin" ,
        local_name: "රළු දත් සහිත ඩොල්ෆින්" ,
        IUCN_status: "LC" ,
        description: "උල් වූ කේතුකාකාර හිසක් සහිත ශක්තිමත් සිරුරක් සහ රැලි නොමැති මෘදු බෑවුම් සහිත කොමඩු ගෙඩියක් ඇත. හොට දිගු වන අතර flippers විශාල හා උල් වේ." ,
        size: "උපතේදී දිග: 1m, වැඩිහිටි දිග: 2.65m, වැඩිහිටි බර: 155 Kg" ,
        colour_pattern: "උඩ අළු පැහැති කළු, රෝස පැහැති බඩ සහ පෘෂ්ඨීය වරල් යට ගිල්වන පැතිවල සැහැල්ලු අළු කේප් එකක්. උදරය, තොල් සහ යටි හකු සුදු පැහැයෙන් යුක්ත වන අතර අඳුරු ඇස් පැල්ලමක් ඇත." ,
        dorsal_fin: "පෘෂ්ඨීය වරල උස, සිහින්, පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "සෑම හකුකම දත්වල රැලි සහිත දාර සහිත දත් යුගල 19-28ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "ගැඹුරු සාගර ජලයේ හමුවන්නේ ඉන්දියානු ජලයේ ඉතා කලාතුරකිනි" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "සෝසා ප්ලම්බියා" ,
        image_path: "Indian-Ocean-Humpback-Dolphin" ,
        local_name: "ඉන්දියන් සාගරයේ හම්ප්බැක් ඩොල්ෆින්" ,
        IUCN_status: "EN" ,
        description: "ශක්තිමත් ශරීරය, මධ්" ,
        size: "උපතේදී දිග: 1m, වැඩිහිටි දිග: 2.6-2.8m, වැඩිහිටි බර: 280 Kg" ,
        colour_pattern: "උඩ අළු පාට කළු, රෝස පාට බඩ. උදරය, තොල් සහ යටි හකු සැහැල්ලු, තොල් සහ යටි හකු සහ පැල්ලම් රෝස පැහැයක් ගනී. අඳුරු ඇස් පැල්ලමක් ඇත." ,
        dorsal_fin: "පෘෂ්ඨීය වරල කෙටි වන අතර උල් වූ සිරුරේ මධ්" ,
        teeth_count: "ඉහළ හනුවේ දත් යුගල 33-39 ක් ද පහළ හකු දත් යුගල 31-37 ක් ද ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "30 m ට අඩු ගැඹුරකින් යුත් වෙරළ ආසන්නයේ නොගැඹුරු ජලයේ, ගංගා මුඛයට ආසන්නව සහ මෝය ආශ්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "සූසා චිනෙන්සිස්" ,
        image_path: "Indo-Pacific-Humpback-Dolphin" ,
        local_name: "ඉන්දු පැසිෆික් හම්ප්බැක් ඩොල්ෆින්" ,
        IUCN_status: "VU" ,
        description: "ශක්තිමත් ශරීරය, මධ්" ,
        size: "උපතේදී දිග: 1m, වැඩිහිටි දිග: 2.7m, වැඩිහිටි බර: 240 Kg" ,
        colour_pattern: "අළු පැහැයට හුරු රෝස පැහැයක් සහිත දෙපස වැඩි රෝස පැහැයක්, මුඛය වටා සහ රෝස පැහැති බඩක්." ,
        dorsal_fin: "පෘෂ්ඨීය වරල් කෙටි වේ" ,
        teeth_count: "ඉහළ හනුවේ දත් යුගල 32-38 ක් ද පහළ හකු යුගල 29-38 ක් ද ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "ඉන්දියාවේ නැගෙනහිර වෙරළ තීරයේ S plumbea සහ chinensis අතර අතිච්ඡාදනය වන ප්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Tursiops aduncus" ,
        image_path: "Indo-Pacific-Bottlenose-Dolphin" ,
        local_name: "ඉන්දු පැසිෆික් බෝතල් නාසය ඩොල්ෆින්" ,
        IUCN_status: "NT" ,
        description: "බල්බ හිසක් සහ මෘදු බෑවුම් සහිත නළලක් සහිත ශක්තිමත් ශරීරයක් ඇත. හොට දිගු වන අතර යටි හකු ඉහළ හකුට වඩා තරමක් දිගු වේ. කැපී පෙනෙන රැල්ලක් පවතී. Flippers කුඩා, උල්." ,
        size: "උපතේදී දිග: 85-112cm, වැඩිහිටි දිග: 2.7m, වැඩිහිටි බර: 230 Kg" ,
        colour_pattern: "දෙපස ලා අළු පැහැති තොප්පියක් සමඟ ඉහළට අළු සහ පෘෂ්ඨීය වරල දෙසට ගිනිදැල් ඉහළ යයි. පැටවුන්ට රෝස පැහැති උදරයක් ඇති අතර වැඩිහිටියන් තුළ කළු පැහැති තිත් දක්නට ලැබේ." ,
        dorsal_fin: "පෘෂ්ඨීය වරල පුළුල් පදනමක් සහිත උසයි" ,
        teeth_count: "සෑම හකුකම දත් යුගල 21-29 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "වෙරළ ආසන්නයේ ඇති ඉන්දියානු ජලයේ රාක්කයේ ටර්සියෝප්ස් ට්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Stenella attenuata" ,
        image_path: "Pan-Tropical-Spotted-Dolphin" ,
        local_name: "පෑන්-නිවර්තන පැල්ලම් සහිත ඩොල්ෆින්" ,
        IUCN_status: "LC" ,
        description: "රැලි සහිත කැපී පෙනෙන කොමඩු ගෙඩියක් සහිත සිහින් සිරුරක් ඇත. පෘෂ්ඨීය වරල උස, සිහින්, පිටුපස මැද ලක්ෂ්" ,
        size: "උපතේදී දිග: 90cm, වැඩිහිටි දිග: 2.4-2.6m, වැඩිහිටි බර: 119 Kg" ,
        colour_pattern: "පැන්ට්" ,
        dorsal_fin: " මධ්" ,
        teeth_count: "සෑම හකුකම කුඩා උල් දත් 35-40ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "පෑන්-නිවර්තන පැල්ලම් සහිත ඩොල්ෆින් වෙරළබඩ සහ වෙරළබඩ ප්" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Stenella longirostris" ,
        image_path: "Spinner-Dolphin" ,
        local_name: "ස්පිනර් ඩොල්ෆින්" ,
        IUCN_status: "DD" ,
        description: "මෘදු බෑවුම් සහිත නළල සහිත ඉතා සිහින් සිරුරක් ඇත. රැල්ලක් ඇති අතර හොට ඉතා දිගු වේ. flippers සිහින් සහ උල් වේ." ,
        size: "උපතේදී දිග: 75-80cm, වැඩිහිටි දිග: 1.5-2.3m, වැඩිහිටි බර: 82 Kg" ,
        colour_pattern: "ඉහළින් අළු පැහැති කළු, පැති දිගේ දිවෙන සැහැල්ලු අළු පටියක් සහ සුදු බඩ (ත්" ,
        dorsal_fin: "පෘෂ්ඨීය වරල උස, සිහින්, පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "සෑම හකුටම දත් යුගල 40-62ක් ඇත (වාමන දඟ පන්දු යවන ඩොල්ෆින් මත්ස්" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "ගැඹුරු අක්වෙරළ ජලයේ සහ ආසන්න වෙරළ ජලය ගැඹුරු සාගර දූපත් අවට දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Stenella coeruleoalba" ,
        image_path: "Striped-Dolphin" ,
        local_name: "ඉරි සහිත ඩොල්ෆින්" ,
        IUCN_status: "LC" ,
        description: "අනෙක් ස්ටෙනෙල්ලා මෙන් ශරීරය සිහින් නොවේ. ඔවුන්ට මෘදු බෑවුම් සහිත නළලක් සහ මධ්" ,
        size: "උපතේදී දිග: 93-100cn, වැඩිහිටි දිග: 2.56m, වැඩිහිටි බර: 155 Kg" ,
        colour_pattern: "අඳුරු තොප්පියක් සහිත ඉහළ අළු කළු. පෘෂ්ඨීය වරල් ඉදිරිපස දෙසට දැල්ලක් සහිත පැත්තේ ලා අළු. අඳුරු ඉරි ඇසේ සිට ගුදය දක්වා දිවෙන අතර ඉහළ හොට අඳුරු වන අතර පහළ හොට කළු තුඩක් සහිත සුදු ය" ,
        dorsal_fin: "පෘෂ්ඨීය වරල ත්" ,
        teeth_count: "සෑම හකුකම දත් යුගල 40-55 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "සාගර ගැඹුරු ජලයේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Delphinus capensis tropicalis" ,
        image_path: "Indo-Pacific-Common-Dolphin" ,
        local_name: "ඉන්දු පැසිෆික් පොදු ඩොල්ෆින්" ,
        IUCN_status: "LC" ,
        description: "මෘදු බෑවුම් සහිත නළලක් සහ කැපී පෙනෙන රැල්ලක් සහිත ඉතා සිහින් සිරුරක් ඇත. ඔවුන්ට ඉතා දිගු හොටක් ඇති අතර ෆ්ලිපර් දිගු, සිහින් සහ උල් වේ." ,
        size: "උපතේදී දිග: 80-100cm, වැඩිහිටි දිග: 2.6m, වැඩිහිටි බර: 235 Kg" ,
        colour_pattern: "උඩින් අළු පැහැයට හුරු කළු, පෘෂ්ඨීය වරලට යටින් කැපී පෙනෙන v-හැඩැති පැය වීදුරු රටාවක් සහිත සැහැල්ලු සුදු බඩක් සහ ෆ්ලිපර් එකට උඩින් කහ පැහැති දැල්ලක්." ,
        dorsal_fin: "පෘෂ්ඨීය වරල උස, සිහින්, විකෘති වූ සහ පිටුපස මැද ලක්ෂ්" ,
        teeth_count: "ඉහළ හනුවේ දත් යුගල 54-67 ක් ද පහළ හකු යුගල 52-64 ක් ද ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "මහාද්වීපික රාක්කයේ ගැඹුරු ජලයේ සහ බෑවුමේ, සමහර විට වෙරළට ආසන්න ගැඹුරු ජලයේ දක්නට ලැබේ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "Lagenodelphis hosei" ,
        image_path: "Fraser's-Dolphin" ,
        local_name: "ෆ්රේසර්ගේ ඩොල්ෆින්" ,
        IUCN_status: "LC" ,
        description: "කැපී පෙනෙන රැල්ලක් සහිත, මෘදු බෑවුම් සහිත නළලක් සහිත ඉතා ස්ථුල ශරීරයක් ඇත. කොමඩු සහ හොට අතර. හොට ම කෙටි හා මුරණ්ඩු ය" ,
        size: "උපතේදී දිග: 1-1.1m, වැඩිහිටි දිග: 2.6-2.7m, වැඩිහිටි බර: 210 Kg" ,
        colour_pattern: "රෝස පැහැති බඩ සහ මුහුණේ සිට ගුදය දක්වා දිවෙන ලා අළු පටියක් සහිත මුදුනේ අළු පැහැය. පහළ හකු මැද සිට ෆ්ලිපර් දක්වා අළු පැහැති තීරුවක් දිස්වන අතර කොමඩු මුදුනේ සිට ඉහළ හකු කෙළවර දක්වා අඳුරු තීරුවක් දිස්වේ. හොටේ අග අඳුරුයි." ,
        dorsal_fin: "පෘෂ්ඨීය වරල කෙටි, ත්" ,
        teeth_count: "සෑම හකුකම දත් යුගල 38-44 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නොදන්නා" ,
        habitat_preferance: "ගැඹුරු මුහුදු ජලයේ දක්නට ලැබෙන සාගර විශේෂ" ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "නියෝෆොකේනා ෆොකේනොයිඩ්ස්" ,
        image_path: "Indo-Pacific-Finless-Porpoise" ,
        local_name: "ඉන්දු-පැසිෆික් වරල් රහිත පෝපොයිස්" ,
        IUCN_status: "VU" ,
        description: "බල්බ හිසක් සහ වටකුරු නාසයක් සහිත ටෝපිඩෝ හැඩැති ශරීරයක් ඇත. හොටක් නැත. Flippers දිගු හා වැරදියි. fluke notched." ,
        size: "උපතේදී දිග: 75-85cm, වැඩිහිටි දිග: 1.5m, වැඩිහිටි බර: 60 Kg" ,
        colour_pattern: "තද අළු සිට දුඹුරු අළු දක්වා ටියුබල් පැල්ලමක් සහිත පිටුපසට ටියුබල් 10-25 පේළි ඇත. පෘෂ්ඨීය වරල් නැත." ,
        dorsal_fin: "පෘෂ්ඨීය වරල් නොමැත" ,
        teeth_count: "ස්පේඩ් හැඩැති දත් එක් එක් හකු වල දත් යුගල 15-22 ක් ඇත" ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "සුන්දරබන්ස් ඇතුළු ඉන්දියාවේ වෙරළ තීරයේ, වෙරළ ආසන්නයේ සහ මෝයවල දක්නට ලැබේ." ,
        type: "Marine Mammals" ,
    },
    {   
        scientific_name: "ප්ලැටනිස්ටා ගංගටිකා" ,
        image_path: "South-Asian-River-Dolphin" ,
        local_name: "දකුණු ආසියානු ගංගා ඩොල්ෆින්" ,
        IUCN_status: "EN" ,
        description: "දකුණු ආසියා ගංගා ඩොල්ෆින් මත්ස්" ,
        size: "උපතේදී දිග: 70-90cm, වැඩිහිටි දිග: 1.6-2.6m, වැඩිහිටි බර: 85 Kg" ,
        colour_pattern: "ඉහළ සහ පිටුපස ලා දුඹුරු සිට දුඹුරු අළු පැහැයක් ගන්නා අතර යටි පැත්ත සැහැල්ලු වේ" ,
        dorsal_fin: "පෘෂ්ඨීය වරල පහත්, කුඩා, ත්" ,
        teeth_count: "ඉහළ හකු දත් යුගල 26-39 ක් සහ පහළ හකු දත් යුගල 26-35 ක් ඇත." ,
        baleen_plate: null,
        throat_grooves: null,
        seasonal_movement: "නේවාසික ජනගහනය" ,
        habitat_preferance: "ඉන්දු, ගංගා, බ්" ,
        type: "Marine Mammals" ,
    },
]


data.sort((a, b) => a.scientific_name.localeCompare(b.scientific_name))

const d: IDatabaseEntry[] = data.map((e,i) => {
    return {
        id: i.toString(),
        ...e
    }
})

export default d